function main() {
const v4 = [13.37];
// v4 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v6 = [1337,1337,1337,1337,1337];
// v6 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v7 = [-1024324723,-1024324723];
// v7 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v8 = {constructor:"object",__proto__:13.37,length:v4};
// v8 = .object(ofGroup: Object, withProperties: ["length", "constructor", "__proto__"])
const v9 = {length:-1024324723,a:13.37,d:1337,valueOf:13.37,c:v4};
// v9 = .object(ofGroup: Object, withProperties: ["length", "a", "d", "valueOf", "__proto__", "c"])
let v10 = v8;
const v15 = [13.37];
// v15 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v17 = [1337,1337,1337,1337,1337];
// v17 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v18 = [-1024324723,-1024324723];
// v18 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v19 = {constructor:"object",__proto__:13.37,length:v15};
// v19 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "length"])
const v20 = {length:-1024324723,a:13.37,d:1337,valueOf:13.37,c:v15};
// v20 = .object(ofGroup: Object, withProperties: ["c", "valueOf", "d", "length", "__proto__", "a"])
let v21 = v19;
const v24 = [1337,1337,1337,1337];
// v24 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
let v25 = v24;
const v29 = [13.37,13.37,13.37,-4294967297];
// v29 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v31 = [13.37,-4294967297,v29];
// v31 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
let v33 = 0;
while (v33 < 1337) {
    const v34 = v33 + 1;
    // v34 = .primitive
    v33 = v34;
}
let v37 = "string";
const v41 = [1337,1337,1337,1337,1337];
// v41 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
function v42(v43,v44,v45,v46) {
    'use strict'
    try {
        v46[3] = v46;
    } catch(v47) {
        const v51 = {length:"N0Xx92zvHQ"};
        // v51 = .object(ofGroup: Object, withProperties: ["__proto__", "length"])
        const v53 = {set:eval,get:v42};
        // v53 = .object(ofGroup: Object, withProperties: ["__proto__"], withMethods: ["get", "set"])
        const v55 = Object.defineProperty(Number,10,v53);
        // v55 = .undefined
        let v58 = 0;
        const v59 = v58 + 1;
        // v59 = .primitive
        v58 = v59;
        const v61 = {set:gc,get:eval};
        // v61 = .object(ofGroup: Object, withProperties: ["__proto__"], withMethods: ["get", "set"])
        const v63 = Object.defineProperty(Number,3500322937,v61);
        // v63 = .undefined
    }
    const v67 = [13.37];
    // v67 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v68 = [];
    // v68 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v69 = {toString:1073741824,e:Function,b:v68,valueOf:Function,a:v67,constructor:Function};
    // v69 = .object(ofGroup: Object, withProperties: ["constructor", "e", "toString", "b", "valueOf", "a", "__proto__"])
    const v73 = {isExtensible:2291304804,apply:v69,getOwnPropertyDescriptor:1337,preventExtensions:2291304804,ownKeys:JSON,deleteProperty:2291304804};
    // v73 = .object(ofGroup: Object, withProperties: ["ownKeys", "getOwnPropertyDescriptor", "isExtensible", "apply", "preventExtensions", "__proto__", "deleteProperty"])
    const v75 = new String(v67,v73);
    // v75 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
    const v76 = JSON.stringify(1337,v75,v75);
    // v76 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
    return v41;
}
const v77 = {deleteProperty:v42,set:v42,getPrototypeOf:v42,call:v42,preventExtensions:v42,isExtensible:v42,construct:v42,get:v42,ownKeys:v42,setPrototypeOf:v42,has:v42};
// v77 = .object(ofGroup: Object, withProperties: ["__proto__"], withMethods: ["get", "getPrototypeOf", "preventExtensions", "deleteProperty", "set", "has", "construct", "call", "setPrototypeOf", "ownKeys", "isExtensible"])
const v79 = new Proxy(v41,v77);
// v79 = .unknown
v79[1] = "MIN_VALUE";
for (let v83 = 0; v83 < 100; v83++) {
}
const v85 = [1337,Infinity,Infinity];
// v85 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v86 = [v37,v85];
// v86 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v87 = v86.toLocaleString();
// v87 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
const v88 = v87.padStart(1337,Infinity);
// v88 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
const v89 = parseFloat(v88);
// v89 = .float
const v92 = [4096];
// v92 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
let v93 = gc;
const v98 = [13.37];
// v98 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v100 = [1337,1337];
// v100 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v101 = [-3132770439,1337,1337];
// v101 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v102 = {constructor:v100,d:v100,a:v101,toString:1337,c:v98};
// v102 = .object(ofGroup: Object, withProperties: ["constructor", "a", "__proto__", "toString", "c", "d"])
const v103 = {constructor:Map,length:13.37,valueOf:v100,b:1337,a:-3132770439};
// v103 = .object(ofGroup: Object, withProperties: ["valueOf", "b", "a", "__proto__", "length", "constructor"])
let v104 = 1337;
const v109 = [13.37,13.37,13.37,13.37,13.37];
// v109 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v111 = [1337];
// v111 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v112 = [-1151066323,v111,isFinite];
// v112 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v113 = {toString:13.37,c:v111,__proto__:v112,valueOf:"tTpktw/d77",constructor:"tTpktw/d77",length:v111};
// v113 = .object(ofGroup: Object, withProperties: ["valueOf", "c", "constructor", "length", "toString", "__proto__"])
const v114 = {toString:13.37};
// v114 = .object(ofGroup: Object, withProperties: ["__proto__", "toString"])
let v115 = 1337;
const v122 = [1337,13.37,"DwTSpuldnd"];
// v122 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v124 = new Uint8Array(v122);
// v124 = .object(ofGroup: Uint8Array, withProperties: ["__proto__", "constructor", "length", "byteOffset", "byteLength", "buffer"], withMethods: ["copyWithin", "filter", "reverse", "includes", "findIndex", "every", "subarray", "keys", "set", "some", "reduce", "reduceRight", "join", "sort", "indexOf", "entries", "forEach", "values", "lastIndexOf", "find", "slice", "fill", "map"])
const v127 = [13.37,13.37,13.37];
// v127 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v128 = v127[Function];
// v128 = .unknown
const v129 = v124.sort(v128);
// v129 = .undefined
const v131 = [13.37,13.37,13.37,13.37];
// v131 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v133 = [1337,1337,1337];
// v133 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v134 = [986843737];
// v134 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v135 = {constructor:v133,toString:"undefined",valueOf:v131,c:v133,__proto__:1337};
// v135 = .object(ofGroup: Object, withProperties: ["toString", "__proto__", "constructor", "c", "valueOf"])
const v136 = {a:v133,b:v133,__proto__:1337,c:v133,e:v131};
// v136 = .object(ofGroup: Object, withProperties: ["a", "b", "e", "c", "__proto__"])
let v137 = v135;
const v139 = {a:Math};
// v139 = .object(ofGroup: Object, withProperties: ["__proto__", "a"])
const v140 = ~"object";
// v140 = .boolean
let v142 = 0;
let v144 = 0;
const v148 = [13.37,13.37,13.37,13.37];
// v148 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v149 = [v148,-1970853828,DataView];
// v149 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v152 = new Float64Array(8);
// v152 = .object(ofGroup: Float64Array, withProperties: ["buffer", "constructor", "byteOffset", "byteLength", "__proto__", "length"], withMethods: ["forEach", "fill", "subarray", "set", "reduce", "join", "slice", "includes", "lastIndexOf", "filter", "find", "reverse", "values", "map", "keys", "reduceRight", "copyWithin", "sort", "some", "indexOf", "entries", "findIndex", "every"])
const v157 = [13.37,13.37,13.37,13.37];
// v157 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v159 = [1337,1337,1337,1337,1337];
// v159 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v160 = ["UflW1mhflT"];
// v160 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v161 = {length:"UflW1mhflT",a:v159,c:-1663921742,toString:v160,constructor:"UflW1mhflT"};
// v161 = .object(ofGroup: Object, withProperties: ["__proto__", "toString", "constructor", "length", "a", "c"])
const v162 = {length:"UflW1mhflT"};
// v162 = .object(ofGroup: Object, withProperties: ["length", "__proto__"])
let v163 = 13.37;
const v168 = [13.37,13.37,13.37,13.37];
// v168 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v170 = [1337,1337,1337];
// v170 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v171 = [v168,v170,"object"];
// v171 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v172 = {};
// v172 = .object(ofGroup: Object, withProperties: ["__proto__"])
const v173 = {toString:3808353909,d:3808353909,e:3808353909,a:v168};
// v173 = .object(ofGroup: Object, withProperties: ["a", "toString", "__proto__", "e", "d"])
let v174 = v168;
const v179 = [13.37,13.37,13.37];
// v179 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v181 = [1337,1337,1337,1337,1337];
// v181 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v182 = [13.37,-4294967296];
// v182 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v183 = {d:"replace",constructor:13.37,b:13.37,c:"replace",e:-4294967296};
// v183 = .object(ofGroup: Object, withProperties: ["c", "d", "__proto__", "constructor", "e", "b"])
const v184 = {e:-4294967296,constructor:v181,c:v179,valueOf:v181};
// v184 = .object(ofGroup: Object, withProperties: ["valueOf", "e", "__proto__", "c", "constructor"])
function v185(v186,v187) {
    const v195 = [13.37,13.37,13.37];
    // v195 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v197 = [1337,1337,1337];
    // v197 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v198 = [v195,v195,Infinity,v195];
    // v198 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v199 = {d:1337,e:13.37,__proto__:v198,length:v197};
    // v199 = .object(ofGroup: Object, withProperties: ["length", "e", "d", "__proto__"])
    const v200 = {c:10,constructor:10,valueOf:v195,__proto__:10,toString:"YjXjEe2.bY"};
    // v200 = .object(ofGroup: Object, withProperties: ["toString", "__proto__", "constructor", "c", "valueOf"])
    let v201 = "YjXjEe2.bY";
    const v206 = [13.37,13.37,13.37];
    // v206 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v208 = "object"[257];
    // v208 = .unknown
    delete v181[-367875910];
    v201.__proto__ = "object";
    for (let v212 = 0; v212 < 100; v212++) {
        const v213 = isFinite(10);
        // v213 = .boolean
    }
    let v216 = 0;
    do {
        v109.toString = parseFloat;
        const v217 = v216 + 1;
        // v217 = .primitive
        v216 = v217;
    } while (v216 < 2);
    const v218 = [];
    // v218 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v219 = {__proto__:"eeeRbEqfAO",constructor:65537,length:v218};
    // v219 = .object(ofGroup: Object, withProperties: ["length", "__proto__", "constructor"])
    const v220 = {toString:"eeeRbEqfAO",d:13.37,length:v219,__proto__:RegExp,valueOf:65537};
    // v220 = .object(ofGroup: Object, withProperties: ["toString", "length", "d", "valueOf", "__proto__"], withMethods: ["__proto__"])
    let v221 = RegExp;
    const v226 = [-2072135974,-2072135974,-2072135974,-2072135974,-2072135974];
    // v226 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v227 = ["undefined",-807842.3563119042,-807842.3563119042];
    // v227 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v228 = {b:2147483647};
    // v228 = .object(ofGroup: Object, withProperties: ["__proto__", "b"])
    function v229(v230,v231) {
        const v232 = v230 in v229;
        // v232 = .boolean
        const v238 = [926222540,926222540,1337,DataView];
        // v238 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
        const v239 = {e:DataView,constructor:1337,valueOf:1337,d:v238};
        // v239 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "valueOf", "constructor", "d"])
        for (let v244 = 0; v244 < 10; v244 = v244 + 10) {
        }
        const v246 = [1337];
        // v246 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
        let v248 = 0;
        for (const v249 in "boolean") {
            let v252 = 0;
            let v254 = 0;
            const v255 = v254 + 1;
            // v255 = .primitive
            for (let v259 = 0; v259 < 100; v259++) {
            }
            const v262 = [];
            // v262 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
            const v263 = {valueOf:v262,length:13.37,d:127,e:127};
            // v263 = .object(ofGroup: Object, withProperties: ["valueOf", "length", "e", "d", "__proto__"])
            let v264 = v263;
            const v265 = 100 - 1;
            // v265 = .primitive
            const v266 = v264[3];
            // v266 = .unknown
            let v268 = 0;
            for (let v272 = 0; v272 < 0; v272++) {
            }
            try {
            } catch(v273) {
                const v278 = [13.37,13.37,13.37];
                // v278 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v281 = [1337,1337,1337,1337,1337];
                // v281 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v282 = [];
                // v282 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v283 = {__proto__:"eeeRbEqfAO",constructor:65537,length:v282};
                // v283 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "length"])
                const v284 = {toString:"eeeRbEqfAO",d:13.37,length:v283,__proto__:RegExp,valueOf:65537};
                // v284 = .object(ofGroup: Object, withProperties: ["valueOf", "length", "toString", "__proto__", "d"], withMethods: ["__proto__"])
                let v285 = RegExp;
                const v290 = [13.37,13.37,13.37,13.37,13.37];
                // v290 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                let v293 = -9007199254740992;
                const v298 = [-1242988596,13.37,13.37,-4294967297];
                // v298 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v300 = [-374203.6377172986,-93687789,v298];
                // v300 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                let v303 = 0;
                while (v303 < 4) {
                    const v304 = v300.push(v293);
                    // v304 = .integer
                    const v305 = v303 + 1;
                    // v305 = .primitive
                    v303 = v305;
                }
                const v306 = [0];
                // v306 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v307 = [v290,v306,Uint8ClampedArray];
                // v307 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v308 = {b:v306,e:Uint8ClampedArray,a:13.37,length:"iterator",valueOf:4294967297};
                // v308 = .object(ofGroup: Object, withProperties: ["b", "__proto__", "e", "valueOf", "length", "a"])
                const v309 = {b:0,e:0,toString:Uint8ClampedArray,d:Uint8ClampedArray};
                // v309 = .object(ofGroup: Object, withProperties: ["e", "b", "toString", "__proto__", "d"])
                let v310 = v290;
                const v315 = [13.37,13.37,13.37,13.37,13.37];
                // v315 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v317 = [13.37];
                // v317 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v318 = [v315,v317,Uint16Array];
                // v318 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v322 = Object(13.37,1337);
                // v322 = .object()
                const v323 = {b:v317,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
                // v323 = .object(ofGroup: Object, withProperties: ["b", "e", "__proto__", "length", "valueOf", "a"])
                const v324 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
                // v324 = .object(ofGroup: Object, withProperties: ["toString", "e", "d", "__proto__", "b"])
                const v326 = [13.37,13.37,13.37,13.37,13.37];
                // v326 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                const v328 = [1337];
                // v328 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                let v329 = v326;
                const v333 = [13.37,13.37];
                // v333 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                for (const v334 in "object") {
                    const v335 = ~v333;
                    // v335 = .boolean
                }
                const v337 = "object".constructor;
                // v337 = .function()
                const v338 = gc + v328;
                // v338 = .primitive
                const v339 = v329 - v337;
                // v339 = .number
                const v341 = [1337];
                // v341 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
                let v342 = v341;
                let v344 = undefined;
                let v346 = 0;
                let v348 = 0;
            }
            const v351 = [13.37];
            // v351 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
            const v355 = v226 & 8;
            // v355 = .integer
            const v356 = v228.__proto__;
            // v356 = .object()
            for (let v357 = 0; v357 < 100; v357++) {
            }
            for (const v358 of "pvU0UUjoya") {
            }
            const v359 = v252 + 1;
            // v359 = .primitive
        }
        const v360 = 926222540 + 1;
        // v360 = .primitive
        for (const v362 in "object") {
        }
        return 0;
    }
    const v364 = [1337];
    // v364 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    let v365 = v364;
    const v366 = [];
    // v366 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v369 = [13.37,13.37];
    // v369 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v370 = [13.37,13.37,-9007199254740992,13.37];
    // v370 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v372 = [1337];
    // v372 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v377 = new Uint16Array(6992);
    // v377 = .object(ofGroup: Uint16Array, withProperties: ["buffer", "byteOffset", "length", "byteLength", "__proto__", "constructor"], withMethods: ["join", "slice", "sort", "reduceRight", "reverse", "forEach", "values", "some", "findIndex", "find", "keys", "map", "filter", "fill", "set", "includes", "subarray", "reduce", "indexOf", "entries", "every", "copyWithin", "lastIndexOf"])
    const v378 = v366.__proto__;
    // v378 = .object()
    v378.__proto__ = v377;
    v370.length = 461300596;
    const v379 = [1071021010,1071021010,1071021010,1071021010];
    // v379 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v381 = [5.0,5.0,5.0];
    // v381 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v382 = [5.0];
    // v382 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v383 = v382.concat(v372,v369,v381,v370,v379);
    // v383 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
    const v384 = v229(v365);
    // v384 = .unknown
    let v394 = 986843737;
    let v396 = 0;
    const v397 = v396 + 1;
    // v397 = .primitive
    const v460 = Symbol.split;
    // v460 = .object(ofGroup: Symbol, withProperties: ["description", "__proto__"])
    "boolean"[v460] = v179;
    const v462 = !v183;
    // v462 = .boolean
    const v509 = "boolean" && 13.37;
    // v509 = .boolean
    for (const v510 in v112) {
        const v513 = new Uint8ClampedArray(48793);
        // v513 = .object(ofGroup: Uint8ClampedArray, withProperties: ["buffer", "length", "byteLength", "constructor", "__proto__", "byteOffset"], withMethods: ["join", "values", "reduceRight", "find", "reverse", "fill", "indexOf", "entries", "forEach", "subarray", "findIndex", "every", "set", "reduce", "slice", "filter", "copyWithin", "keys", "lastIndexOf", "sort", "map", "some", "includes"])
    }
    let v516 = 0;
    do {
        "boolean".e = v100;
        const v517 = v516 + 1;
        // v517 = .primitive
        v516 = v517;
    } while (v516 < 9);
    let v522 = 0;
    const v525 = eval(-3394606452);
    // v525 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
    const v528 = 4 + 1;
    // v528 = .primitive
    return gc;
}
let v545 = 0;
const v549 = v185();
// v549 = .unknown
let v550 = v184;
const v552 = [1337];
// v552 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
let v553 = v552;
let v555 = undefined;
const v566 = [13.37,13.37,13.37,13.37];
// v566 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v568 = [1337];
// v568 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v569 = {b:-2619420865,constructor:13.37};
// v569 = .object(ofGroup: Object, withProperties: ["b", "__proto__", "constructor"])
const v570 = {d:"isConcatSpreadable"};
// v570 = .object(ofGroup: Object, withProperties: ["d", "__proto__"])
let v571 = -2619420865;
const v576 = [13.37,13.37,13.37,13.37,13.37];
// v576 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v582 = [13.37,v173,13.37,13.37,13.37];
// v582 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v584 = [1337,1337,1337,1337];
// v584 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v585 = [v582,1337,13.37];
// v585 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v586 = {b:"toStringTag",c:v585};
// v586 = .object(ofGroup: Object, withProperties: ["c", "b", "__proto__"])
const v587 = {valueOf:v584,length:eval};
// v587 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["length"])
let v588 = 1337;
const v593 = [13.37,13.37,13.37];
// v593 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v595 = [1337,1337,1337,1337];
// v595 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v596 = 1337 > eval;
// v596 = .boolean
const v597 = v585[2403828005];
// v597 = .unknown
v587.length = 1337;
const v599 = !v582;
// v599 = .boolean
"toStringTag".c = v587;
const v600 = [Uint8ClampedArray,13.37];
// v600 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v601 = {d:-1024,c:v600,toString:v595,valueOf:v600};
// v601 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "d", "c", "toString"])
const v602 = {c:v601,e:v600,toString:v595};
// v602 = .object(ofGroup: Object, withProperties: ["c", "e", "__proto__", "toString"])
let v603 = Uint8ClampedArray;
let v610 = 0;
const v611 = v610 + 1;
// v611 = .primitive
const v613 = [13.37,13.37];
// v613 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v615 = [1337,1337,1337,1337,1337];
// v615 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v616 = [];
// v616 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v617 = {c:1337,b:-3170815044,d:1337,__proto__:1337};
// v617 = .object(ofGroup: Object, withProperties: ["d", "__proto__", "b", "c"])
const v618 = {e:"__proto__",a:1337,__proto__:eval,constructor:1337,c:v617,b:Math,toString:"__proto__"};
// v618 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "e", "a", "toString", "b", "c"], withMethods: ["__proto__"])
let v619 = 13.37;
const v624 = [13.37,13.37,13.37,13.37];
// v624 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v626 = [1337];
// v626 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v627 = [];
// v627 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v628 = {valueOf:v626,__proto__:13.37,a:Number,c:Number,b:Number};
// v628 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["b", "a", "c"])
const v629 = {__proto__:v626,a:v626,constructor:Number,e:13.37,length:"number",b:13.37};
// v629 = .object(ofGroup: Object, withProperties: ["b", "length", "a", "__proto__", "e"], withMethods: ["constructor"])
let v630 = v624;
const v635 = [13.37,13.37];
// v635 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v637 = [1337,1337,1337,1337,1337];
// v637 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v638 = [10,DataView,"symbol"];
// v638 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v639 = {toString:v635,e:"symbol",a:13.37,d:DataView,constructor:v638,valueOf:v635};
// v639 = .object(ofGroup: Object, withProperties: ["a", "constructor", "e", "__proto__", "toString", "valueOf", "d"])
const v640 = {length:v639,a:"symbol"};
// v640 = .object(ofGroup: Object, withProperties: ["a", "length", "__proto__"])
const v644 = [13.37,13.37,13.37,13.37,13.37];
// v644 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v646 = [1337,1337,1337,1337];
// v646 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v647 = [v646];
// v647 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v648 = {constructor:v647,toString:v646,a:v647,c:v647,__proto__:isFinite,length:v647};
// v648 = .object(ofGroup: Object, withProperties: ["__proto__", "a", "constructor", "length", "toString", "c"], withMethods: ["__proto__"])
const v649 = {toString:13.37,length:1337};
// v649 = .object(ofGroup: Object, withProperties: ["length", "__proto__", "toString"])
function v651(v652,v653) {
    const v655 = {__proto__:536870912};
    // v655 = .object(ofGroup: Object, withProperties: ["__proto__"])
    with (v655) {
        let v660 = 0;
        __proto__[0] = v651;
    }
    function v664(v665,v666) {
        for (const v668 in "boolean") {
            for (const v672 in "boolean") {
                let v675 = 0;
                do {
                    const v709 = {__proto__:536870912};
                    // v709 = .object(ofGroup: Object, withProperties: ["__proto__"])
                    const v719 = !1337;
                    // v719 = .boolean
                } while (0 < 8);
            }
        }
        return v33;
    }
    return 1000;
}
const v723 = v651(1024,4.0);
// v723 = .unknown
let v726 = 1903240934;
let v730 = 0;
const v731 = v730 + 1;
// v731 = .primitive
v730 = v731;
const v737 = [1.7976931348623157e+308];
// v737 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v739 = [255,255,255];
// v739 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v740 = {a:255,toString:isFinite,c:v737,__proto__:v739,valueOf:DataView,constructor:"gM8oAednYn"};
// v740 = .object(ofGroup: Object, withProperties: ["a", "valueOf", "__proto__", "constructor", "c"], withMethods: ["toString"])
const v741 = {toString:v737,valueOf:v740,d:255,constructor:536870912};
// v741 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "d", "constructor", "toString"])
const v742 = RegExp.apply(v741,RegExp);
// v742 = .unknown
const v743 = [13.37,13.37,-4261300175,13.37];
// v743 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v745 = [1337,1337];
// v745 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v746 = ["MAX_VALUE","MAX_VALUE"];
// v746 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v747 = {b:"MAX_VALUE",length:v745,c:v746};
// v747 = .object(ofGroup: Object, withProperties: ["b", "__proto__", "length", "c"])
const v748 = {constructor:v743,c:13.37,d:13.37};
// v748 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "c", "d"])
let v749 = v747;
const v751 = [1337,v749,1337,1337];
// v751 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
"tTpktw/d77".length = 13.37;
const v753 = v751.indexOf(0,v748);
// v753 = .integer
const v755 = {get:eval};
// v755 = .object(ofGroup: Object, withProperties: ["__proto__"], withMethods: ["get"])
const v757 = Object.defineProperty(v586,"e",v755);
// v757 = .undefined
let v760 = 0;
const v761 = v760 + 1;
// v761 = .primitive
v760 = v761;
const v762 = eval("__proto__");
// v762 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
const v763 = [1337,1337,1337,1337];
// v763 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v764 = [];
// v764 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v765 = {valueOf:v576,a:13.37,toString:"PI",d:v576,b:13.37,e:1000};
// v765 = .object(ofGroup: Object, withProperties: ["d", "a", "e", "toString", "b", "valueOf", "__proto__"])
const v766 = {c:v765,__proto__:parseInt};
// v766 = .object(ofGroup: Object, withProperties: ["__proto__", "c"], withMethods: ["__proto__"])
let v767 = 1337;
const v770 = "symbol".replace("symbol","symbol");
// v770 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
let v771 = RegExp;
const v773 = new Int16Array(v770);
// v773 = .object(ofGroup: Int16Array, withProperties: ["length", "byteLength", "__proto__", "byteOffset", "constructor", "buffer"], withMethods: ["lastIndexOf", "fill", "join", "reduce", "some", "findIndex", "entries", "map", "slice", "reverse", "sort", "set", "indexOf", "find", "copyWithin", "subarray", "includes", "values", "keys", "filter", "forEach", "every", "reduceRight"])
const v774 = v771.apply(v770,v773);
// v774 = .unknown
let v778 = 10;
const v782 = [13.37,v185];
// v782 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v783 = [13.37,v782];
// v783 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v785 = Function("symbol",v783);
// v785 = .unknown
let v786 = 0;
let v792 = 0;
let v795 = 0;
let v796 = 0;
const v801 = v786 + 1;
// v801 = .primitive
for (let v805 = 0; v805 < 9; v805++) {
    const v807 = Symbol.toStringTag;
    // v807 = .object(ofGroup: Symbol, withProperties: ["description", "__proto__"])
    v179[v807] = v805;
}
const v808 = "object"[-3753695015];
// v808 = .unknown
const v809 = v172 in v137;
// v809 = .boolean
let v812 = 0;
const v813 = v812 + 1;
// v813 = .primitive
v812 = v813;
v182.c = 13.37;
const v814 = new Float64Array(v157);
// v814 = .object(ofGroup: Float64Array, withProperties: ["buffer", "constructor", "byteOffset", "byteLength", "__proto__", "length"], withMethods: ["forEach", "fill", "subarray", "set", "reduce", "join", "slice", "includes", "lastIndexOf", "filter", "find", "reverse", "values", "map", "keys", "reduceRight", "copyWithin", "sort", "some", "indexOf", "entries", "findIndex", "every"])
const v815 = v172[2070038973];
// v815 = .unknown
"object"[-2147483649] = v157;
const v816 = parseInt("object");
// v816 = .integer
const v817 = v152.sort();
// v817 = .undefined
const v818 = Function(v742);
// v818 = .unknown
const v820 = [Infinity,Infinity,Infinity];
// v820 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v821 = [v93,v820];
// v821 = .object(ofGroup: Array, withProperties: ["constructor", "length", "__proto__"], withMethods: ["toString", "push", "find", "sort", "keys", "flat", "forEach", "lastIndexOf", "concat", "reverse", "indexOf", "toLocaleString", "splice", "reduceRight", "shift", "entries", "slice", "pop", "findIndex", "every", "unshift", "map", "flatMap", "includes", "fill", "reduce", "copyWithin", "filter", "join", "some", "values"])
const v822 = v821.toLocaleString();
// v822 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["replace", "padStart", "charCodeAt", "repeat", "indexOf", "trim", "lastIndexOf", "padEnd", "concat", "split", "startsWith", "codePointAt", "endsWith", "charAt", "slice", "substring", "includes"])
const v823 = {c:v822,d:v92};
// v823 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "c"])
let v824 = v823;
"boolean".constructor = "number";
const v825 = ~v627;
// v825 = .boolean
"gM8oAednYn".__proto__ = RegExp;
const v826 = gc();
// v826 = .undefined
}
%NeverOptimizeFunction(main);
main();
