function main() {
const v4 = [13.37,13.37,13.37,13.37];
// v4 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v6 = [1337,1337,1337,1337];
// v6 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v7 = [1805143900];
// v7 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v8 = {e:13.37,b:"symbol",toString:v4,d:undefined,length:v7};
// v8 = .object(ofGroup: Object, withProperties: ["b", "e", "toString", "length", "__proto__", "d"])
const v9 = {length:1805143900,c:13.37,e:"symbol",toString:"symbol",constructor:v4,__proto__:"symbol"};
// v9 = .object(ofGroup: Object, withProperties: ["e", "length", "toString", "c", "__proto__", "constructor"])
let v10 = 13.37;
const v15 = [13.37,13.37,13.37];
// v15 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v17 = [1337];
// v17 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v18 = [3156875969,3156875969,1337,Int16Array];
// v18 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v19 = {constructor:v18,c:v18,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v19 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "constructor", "d", "c", "a"])
const v20 = {e:Int16Array,constructor:1337,valueOf:1337,d:v18};
// v20 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "d", "constructor", "e"])
let v21 = v17;
const v26 = [13.37,13.37,13.37];
// v26 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v28 = [1337];
// v28 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v29 = [3156875969,3156875969,1337,DataView];
// v29 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v30 = {constructor:v29,c:v29,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v30 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "c", "a", "constructor", "e"])
const v31 = {e:DataView,constructor:1337,valueOf:1337,d:v29};
// v31 = .object(ofGroup: Object, withProperties: ["d", "e", "constructor", "__proto__", "valueOf"])
let v32 = v28;
const v37 = [13.37,13.37,13.37];
// v37 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v39 = [1337];
// v39 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v40 = [3156875969,3156875969,1337,DataView];
// v40 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v41 = {constructor:v40,c:v40,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v41 = .object(ofGroup: Object, withProperties: ["a", "e", "__proto__", "c", "constructor", "d"])
const v42 = {e:DataView,constructor:1337,valueOf:1337,d:v40};
// v42 = .object(ofGroup: Object, withProperties: ["constructor", "valueOf", "d", "__proto__", "e"])
let v43 = v39;
const v47 = [13.37,13.37];
// v47 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v49 = [1337,1337,1337,1337];
// v49 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v54 = [13.37,13.37,13.37];
// v54 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v56 = [1337];
// v56 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v57 = [3156875969,3156875969,1337,DataView];
// v57 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v58 = {constructor:v57,c:v57,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v58 = .object(ofGroup: Object, withProperties: ["d", "c", "a", "e", "__proto__", "constructor"])
const v59 = {e:DataView,constructor:1337,valueOf:1337,d:v57};
// v59 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "d", "valueOf", "constructor"])
let v60 = v56;
const v65 = [371375.4036167406,371375.4036167406,371375.4036167406];
// v65 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v67 = [1337];
// v67 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v68 = [3156875969,3156875969,1337,DataView];
// v68 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v69 = {constructor:v68,c:v68,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
// v69 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "d", "c", "a", "e"])
const v70 = {c:DataView,constructor:1337,valueOf:1337,d:v68};
// v70 = .object(ofGroup: Object, withProperties: ["c", "__proto__", "valueOf", "d", "constructor"])
let v71 = v67;
const v76 = [13.37,13.37,13.37];
// v76 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v78 = [1337];
// v78 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v79 = [3156875969,3156875969,1337,DataView];
// v79 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v80 = {constructor:v79,c:v79,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v80 = .object(ofGroup: Object, withProperties: ["constructor", "d", "c", "a", "__proto__", "e"])
const v81 = {e:DataView,constructor:1337,valueOf:1337,d:v79};
// v81 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "constructor", "d", "e"])
const v84 = [13.37,13.37];
// v84 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v86 = [1337,1337,1337,1337];
// v86 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v87 = {c:13.37};
// v87 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
const v88 = {d:gc,valueOf:v86};
// v88 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
let v89 = 1337;
const v90 = v84[1024];
// v90 = .unknown
let v93 = 0;
do {
    const v94 = v90 - 1;
    // v94 = .primitive
    const v95 = v93 + 1;
    // v95 = .primitive
    let v97 = 0;
    v93 = v95;
} while (v93 < 3);
const v102 = [13.37,13.37];
// v102 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v104 = [1337,1337,1337,1337];
// v104 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
const v105 = "object".constructor;
// v105 = .function()
for (const v106 in "object") {
    const v111 = [13.37,13.37,13.37];
    // v111 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v113 = [1337];
    // v113 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v114 = [3156875969,3156875969,1337,DataView];
    // v114 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v115 = {constructor:v114,c:v114,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v115 = .object(ofGroup: Object, withProperties: ["a", "constructor", "d", "__proto__", "c", "e"])
    const v116 = {e:DataView,constructor:1337,valueOf:1337,d:v114};
    // v116 = .object(ofGroup: Object, withProperties: ["constructor", "d", "__proto__", "e", "valueOf"])
    const v121 = [371375.4036167406,371375.4036167406,371375.4036167406];
    // v121 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v123 = [1337];
    // v123 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v124 = [3156875969,3156875969,1337,DataView];
    // v124 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v125 = {constructor:v124,c:v124,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
    // v125 = .object(ofGroup: Object, withProperties: ["constructor", "c", "__proto__", "a", "e", "d"])
    const v126 = {e:DataView,constructor:1337,valueOf:1337,d:v124};
    // v126 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "e", "d", "valueOf"])
    let v127 = v123;
    const v132 = [13.37,13.37,13.37];
    // v132 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v134 = [1337];
    // v134 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v135 = [3156875969,3156875969,1337,DataView];
    // v135 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v136 = {e:DataView,constructor:1337,valueOf:1337,d:v135};
    // v136 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "valueOf", "e", "d"])
    let v137 = v134;
    const v140 = [13.37,13.37];
    // v140 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v142 = [1337,1337,1337,1337];
    // v142 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v143 = [13.37,v140];
    // v143 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v144 = {c:13.37};
    // v144 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
    const v145 = {d:gc,valueOf:v142};
    // v145 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
    let v146 = 1337;
    const v147 = v140[1024];
    // v147 = .unknown
    let v150 = 0;
    do {
        const v151 = v147 - 1;
        // v151 = .primitive
        const v152 = v150 + 1;
        // v152 = .primitive
        v150 = v152;
    } while (v150 < 3);
    const v157 = [13.37,13.37];
    // v157 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v159 = [1337,1337,1337,1337];
    // v159 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v160 = "object".constructor;
    // v160 = .function()
    for (const v161 in "object") {
        const v162 = ~v157;
        // v162 = .boolean
        const v167 = [13.37,13.37,13.37];
        // v167 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v169 = [1337];
        // v169 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v170 = [3156875969,3156875969,1337,DataView];
        // v170 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v171 = {constructor:v170,c:v170,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
        // v171 = .object(ofGroup: Object, withProperties: ["c", "e", "a", "d", "__proto__", "constructor"])
        const v172 = {e:DataView,constructor:1337,valueOf:1337,d:v170};
        // v172 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "valueOf", "d", "e"])
        let v173 = v169;
        const v178 = [13.37,13.37,13.37];
        // v178 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v180 = [1337];
        // v180 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v181 = [3156875969,3156875969,1337,DataView];
        // v181 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v182 = {constructor:v181,c:v181,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
        // v182 = .object(ofGroup: Object, withProperties: ["d", "e", "a", "c", "__proto__", "constructor"])
        const v183 = {e:DataView,constructor:1337,valueOf:1337,d:v181};
        // v183 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "e", "d", "valueOf"])
        let v184 = v180;
        const v187 = [13.37,13.37];
        // v187 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v189 = [1337,1337,1337,1337];
        // v189 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v190 = [13.37,v187];
        // v190 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v191 = {d:gc,valueOf:v189};
        // v191 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
        let v192 = 1337;
        const v193 = v187[1024];
        // v193 = .unknown
        let v196 = 0;
        do {
            const v197 = v193 - 1;
            // v197 = .primitive
            const v198 = v196 + 1;
            // v198 = .primitive
            v196 = v198;
        } while (v196 < -4294967295);
        const v203 = [13.37,13.37];
        // v203 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v205 = [1337,1337,1337,1337];
        // v205 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v206 = "object".constructor;
        // v206 = .function()
        for (const v207 in 0) {
            const v208 = ~v203;
            // v208 = .boolean
        }
        const v209 = v205 + 1;
        // v209 = .primitive
        const v210 = v205.toString();
        // v210 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["endsWith", "split", "padEnd", "repeat", "lastIndexOf", "substring", "slice", "startsWith", "includes", "charCodeAt", "padStart", "concat", "trim", "replace", "indexOf", "charAt", "codePointAt"])
        "object"[1] = 1337;
        const v211 = [v135,v203];
        // v211 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
        const v212 = {c:13.37};
        // v212 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
        const v213 = {d:gc,valueOf:v205};
        // v213 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
        let v214 = 1337;
        const v216 = Object();
        // v216 = .object()
        v196 = -4294967295;
        const v217 = {__proto__:-4294967295,constructor:v196,d:"boolean",valueOf:v193,length:13.37};
        // v217 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "constructor", "d", "length"])
    }
    const v219 = v159 + 1;
    // v219 = .primitive
    const v220 = v159.toString();
    // v220 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["endsWith", "split", "padEnd", "repeat", "lastIndexOf", "substring", "slice", "startsWith", "includes", "charCodeAt", "padStart", "concat", "trim", "replace", "indexOf", "charAt", "codePointAt"])
    "object"[1] = 1337;
    const v221 = [13.37,v157];
    // v221 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v222 = {c:13.37};
    // v222 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v223 = {d:gc,valueOf:v159};
    // v223 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
    let v225 = 1337;
    const v227 = Object();
    // v227 = .object()
    v150 = 3;
    const v228 = {__proto__:3,constructor:v150,d:v144,valueOf:v147,length:13.37};
    // v228 = .object(ofGroup: Object, withProperties: ["d", "valueOf", "length", "constructor", "__proto__"])
    let v230 = v113;
    const v235 = [13.37,13.37,13.37];
    // v235 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v237 = [1337];
    // v237 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v238 = [3156875969,3156875969,1337,DataView];
    // v238 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v239 = {constructor:v238,c:v238,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v239 = .object(ofGroup: Object, withProperties: ["d", "constructor", "c", "__proto__", "a", "e"])
    const v240 = {e:DataView,constructor:1337,valueOf:1337,d:v238};
    // v240 = .object(ofGroup: Object, withProperties: ["d", "valueOf", "__proto__", "constructor", "e"])
    let v241 = v237;
    const v246 = [13.37,13.37,13.37];
    // v246 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v248 = [1337];
    // v248 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v249 = [3156875969,3156875969,1337,DataView];
    // v249 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v250 = {constructor:v249,c:v249,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v250 = .object(ofGroup: Object, withProperties: ["constructor", "d", "e", "c", "__proto__", "a"])
    const v251 = {e:DataView,constructor:1337,valueOf:1337,d:v249};
    // v251 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "e", "valueOf", "d"])
    let v252 = v248;
    const v257 = [371375.4036167406,371375.4036167406,371375.4036167406];
    // v257 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v259 = [1337];
    // v259 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v260 = [3156875969,3156875969,1337,DataView];
    // v260 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v261 = {constructor:v260,c:v260,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
    // v261 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "a", "constructor", "d", "c"])
    const v262 = {e:DataView,constructor:1337,valueOf:1337,d:v260};
    // v262 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "valueOf", "constructor", "d"])
    let v263 = v259;
    const v284 = [3156875969,3156875969,1337,DataView];
    // v284 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v285 = {e:DataView,constructor:1337,valueOf:1337,d:v284};
    // v285 = .object(ofGroup: Object, withProperties: ["e", "d", "constructor", "valueOf", "__proto__"])
    let v292 = 0;
    const v293 = !v292;
    // v293 = .boolean
    v292 = v293;
    v285.constructor = 13.37;
    let v303 = 0;
    const v304 = Object.prototype;
    // v304 = .object()
    const v305 = v303 + 1;
    // v305 = .primitive
    v303 = v305;
    const v306 = [13.37,13.37,13.37];
    // v306 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v309 = [1337];
    // v309 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    for (let v313 = 0; v313 < 0; v313++) {
    }
    const v315 = v306.toLocaleString();
    // v315 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["endsWith", "split", "padEnd", "repeat", "lastIndexOf", "substring", "slice", "startsWith", "includes", "charCodeAt", "padStart", "concat", "trim", "replace", "indexOf", "charAt", "codePointAt"])
    v102.length = 2;
    const v317 = [1337];
    // v317 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v318 = [3156875969,3156875969,1337,DataView];
    // v318 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v319 = {constructor:v318,c:v318,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v319 = .object(ofGroup: Object, withProperties: ["constructor", "e", "c", "d", "__proto__", "a"])
    const v320 = {e:DataView,constructor:1337,valueOf:1337,d:v318};
    // v320 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "constructor", "d", "valueOf"])
    let v321 = v317;
    const v326 = [13.37,13.37,13.37];
    // v326 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v328 = [1337];
    // v328 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v329 = [3156875969,3156875969,1337,ArrayBuffer];
    // v329 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v330 = {constructor:v329,c:v329,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v330 = .object(ofGroup: Object, withProperties: ["c", "a", "constructor", "__proto__", "e", "d"])
    const v331 = {e:ArrayBuffer,constructor:1337,valueOf:1337,d:v329};
    // v331 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "d", "e", "constructor"])
    let v332 = v328;
    const v337 = [13.37,v81,13.37];
    // v337 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v339 = [1337];
    // v339 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v340 = [3156875969,3156875969,1337,DataView];
    // v340 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v341 = {constructor:v340,c:v340,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v341 = .object(ofGroup: Object, withProperties: ["a", "d", "c", "e", "__proto__", "constructor"])
    const v342 = {e:DataView,constructor:1337,valueOf:1337,d:v340};
    // v342 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "valueOf", "e", "d"])
    let v343 = v339;
    const v346 = Object();
    // v346 = .object()
    const v349 = Object(1337,v346,13.37,v331,3156875969);
    // v349 = .object()
    for (let v353 = 0; v353 < 10; v353++) {
        const v354 = v353 + v330;
        // v354 = .primitive
    }
    const v356 = [1337];
    // v356 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    let v357 = v356;
    const v359 = [13.37,13.37,13.37];
    // v359 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v361 = [2];
    // v361 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    let v362 = v361;
    v362[0] = v361;
    const v365 = [13.37,13.37,13.37];
    // v365 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v367 = [1337];
    // v367 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v368 = [3156875969,3156875969,1337,DataView];
    // v368 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v369 = {constructor:v368,c:v346,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v369 = .object(ofGroup: Object, withProperties: ["__proto__", "a", "constructor", "e", "d", "c"])
    const v370 = {e:DataView,constructor:1337,valueOf:1337,d:v368};
    // v370 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "valueOf", "constructor", "d"])
    let v371 = v367;
    const v375 = [13.37,13.37];
    // v375 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    "boolean"[v340] = 1;
    const v377 = [1337,1337,1337,1337];
    // v377 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v378 = [13.37,v375];
    // v378 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    const v379 = {c:13.37};
    // v379 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v380 = {d:gc,valueOf:v377};
    // v380 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
    let v381 = 1337;
    const v382 = v375[1024];
    // v382 = .unknown
    let v384 = 0;
    for (const v385 in "boolean") {
        let v388 = 0;
        do {
            try {
                let v391 = 0;
                const v392 = v391 + 1;
                // v392 = .primitive
                v391 = v392;
                for (let v397 = 0; v397 < 4; v397++) {
                }
            } catch(v398) {
                if (v398) {
                    let v401 = 0;
                    for (let v405 = 0; v405 < 0; v405++) {
                    }
                } else {
                    try {
                    } catch(v406) {
                    }
                }
            }
            const v407 = v388 + 1;
            // v407 = .primitive
            v388 = v407;
        } while (v388 < 8);
    }
    const v408 = v384 + 1;
    // v408 = .primitive
    v384 = v408;
    let v422 = 0;
    const v423 = v422 + 1;
    // v423 = .primitive
    v422 = v423;
    const v427 = Object(v143,v262,gc);
    // v427 = .object()
    const v428 = v17.flat(1337);
    // v428 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["forEach", "filter", "unshift", "slice", "splice", "reverse", "reduce", "join", "reduceRight", "some", "pop", "copyWithin", "concat", "flatMap", "shift", "push", "lastIndexOf", "fill", "entries", "sort", "includes", "map", "toString", "values", "indexOf", "keys", "every", "flat", "toLocaleString", "find", "findIndex"])
    continue;
    v115.valueOf = gc;
    const v429 = {...v70,...v58};
    // v429 = .object(ofGroup: Object, withProperties: ["valueOf", "a", "constructor", "e", "d", "c", "__proto__"])
}
}
%NeverOptimizeFunction(main);
main();
