function main() {
const v4 = {valueOf:1337,c:3971043784,b:13.37,a:"number"};
// v4 = .object(ofGroup: Object, withProperties: ["valueOf", "c", "a", "__proto__", "b"])
const v9 = [1337,1337,1337,1337];
// v9 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v10 = {a:-4294967297,valueOf:"function",b:1337,length:v9,d:13.37};
// v10 = .object(ofGroup: Object, withProperties: ["__proto__", "b", "d", "a", "length", "valueOf"])
function v16(v17,v18) {
    const v19 = v17 in v16;
    // v19 = .boolean
    const v25 = [3156875969,3156875969,1337,DataView];
    // v25 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v26 = {constructor:v25,c:v25,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v26 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "c", "d", "a", "constructor"])
    const v27 = {e:DataView,constructor:1337,valueOf:1337,d:v25};
    // v27 = .object(ofGroup: Object, withProperties: ["d", "e", "__proto__", "valueOf", "constructor"])
    const v31 = [1337];
    // v31 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    let v33 = 0;
    for (const v34 in "boolean") {
        let v37 = 0;
        do {
            let v39 = 0;
            const v40 = v39 + 1;
            // v40 = .primitive
            v39 = v40;
            for (let v44 = 0; v44 < 100; v44++) {
            }
            const v47 = [];
            // v47 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
            const v48 = {valueOf:v47,length:13.37,d:127,e:127};
            // v48 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "d", "e", "length"])
            let v49 = v48;
            const v50 = v49 + 1;
            // v50 = .primitive
            const v51 = v49[3];
            // v51 = .unknown
            let v53 = 0;
            for (let v57 = 0; v57 < 0; v57++) {
            }
            try {
            } catch(v58) {
            }
            const v62 = [13.37];
            // v62 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
            for (let v66 = 0; v66 < 100; v66++) {
            }
            for (const v67 of "pvU0UUjoya") {
                v62.__proto__ = "pvU0UUjoya";
            }
            let v68 = 13.37;
            const v69 = v37 + 1;
            // v69 = .primitive
            v37 = v69;
        } while (v37 < 8);
    }
    v27.constructor = v17;
    const v70 = v27.__proto__;
    // v70 = .object()
    const v71 = 1337 && v70;
    // v71 = .boolean
    const v72 = "species"[0];
    // v72 = .unknown
    let v73 = 3156875969;
    const v74 = v33 + 1;
    // v74 = .primitive
    v33 = v74;
    const v80 = [13.37,13.37,13.37,13.37,13.37];
    // v80 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v82 = [1337];
    // v82 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v83 = [v80,v82,Uint16Array];
    // v83 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v84 = {b:v82,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v84 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "valueOf", "b", "a", "length"])
    const v85 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v85 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "toString", "e", "b"])
    let v86 = v80;
    const v91 = [13.37,13.37,13.37,13.37,13.37];
    // v91 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v93 = [1337];
    // v93 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v94 = [v91,v93,Uint16Array];
    // v94 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v95 = {b:v93,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v95 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "length", "e", "b", "a"])
    const v96 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v96 = .object(ofGroup: Object, withProperties: ["e", "d", "__proto__", "toString", "b"])
    let v97 = v91;
    const v102 = [13.37,13.37,13.37,13.37,13.37];
    // v102 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v104 = [1337];
    // v104 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v105 = [v102,v104,"iterator"];
    // v105 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v106 = {b:v104,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v106 = .object(ofGroup: Object, withProperties: ["__proto__", "b", "valueOf", "e", "a", "length"])
    let v107 = v102;
    const v110 = [13.37,13.37];
    // v110 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v112 = [1337,1337,1337,1337];
    // v112 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v113 = "object".constructor;
    // v113 = .function()
    for (const v114 in "object") {
        const v115 = ~v110;
        // v115 = .boolean
    }
    const v116 = v112 + 1;
    // v116 = .primitive
    const v117 = v112.toString();
    // v117 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
    "object"[1] = 1337;
    const v122 = [13.37,13.37,13.37,13.37,13.37];
    // v122 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v124 = [v97];
    // v124 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v125 = [v122,v124,Uint16Array];
    // v125 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    v124.constructor = v122;
    const v126 = "iterator" != 4294967297;
    // v126 = .boolean
    for (let v130 = 0; v130 < 6; v130++) {
        "iterator".e = v122;
    }
    v125.valueOf = 13.37;
    const v131 = {b:v124,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v131 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "b", "e", "length", "a"])
    const v132 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v132 = .object(ofGroup: Object, withProperties: ["toString", "__proto__", "b", "e", "d"])
    let v137 = 0;
    while (v137 < 6) {
        const v138 = Array();
        // v138 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
        const v139 = v137 + 1;
        // v139 = .primitive
        v137 = v139;
    }
    let v140 = v107;
    const v142 = Symbol.toStringTag;
    // v142 = .object(ofGroup: Symbol, withProperties: ["__proto__", "description"])
    v9[v142] = v96;
    let v145 = 0;
    delete "iterator"[65535];
    const v146 = v145 + 1;
    // v146 = .primitive
    v145 = v146;
    const v149 = [13.37,13.37,13.37,13.37,13.37];
    // v149 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v151 = [1337];
    // v151 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v152 = [v149,v151,Uint16Array];
    // v152 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v153 = {b:v151,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v153 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "valueOf", "length", "b", "a"])
    const v154 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v154 = .object(ofGroup: Object, withProperties: ["b", "d", "toString", "e", "__proto__"])
    let v155 = v149;
    const v160 = [13.37,13.37,13.37,13.37,13.37];
    // v160 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v162 = [1337];
    // v162 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v163 = [v160,v162,Uint16Array];
    // v163 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v164 = {b:v162,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v164 = .object(ofGroup: Object, withProperties: ["a", "__proto__", "b", "e", "length", "valueOf"])
    const v165 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v165 = .object(ofGroup: Object, withProperties: ["b", "__proto__", "e", "toString", "d"])
    let v166 = v160;
    const v168 = [13.37,13.37,13.37,13.37,13.37];
    // v168 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v171 = 1337 == 13.37;
    // v171 = .boolean
    const v176 = [13.37,13.37,13.37,13.37,13.37];
    // v176 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v178 = [1337];
    // v178 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v179 = [v176,v178,Uint16Array];
    // v179 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v180 = {b:v178,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v180 = .object(ofGroup: Object, withProperties: ["valueOf", "length", "e", "b", "a", "__proto__"])
    const v181 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v181 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "toString", "b", "d"])
    let v182 = v176;
    const v187 = [13.37,13.37,13.37,13.37,13.37];
    // v187 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v189 = [1337];
    // v189 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v190 = [v187,v189,Uint16Array];
    // v190 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v191 = {b:v189,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v191 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "a", "b", "e", "length"])
    const v192 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v192 = .object(ofGroup: Object, withProperties: ["d", "b", "e", "__proto__", "toString"])
    const v197 = [13.37,13.37,13.37,13.37,13.37];
    // v197 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v199 = v189.push(v197);
    // v199 = .integer
    const v200 = [1337];
    // v200 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v201 = [v197,v200,Uint16Array];
    // v201 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v202 = {b:v200,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v202 = .object(ofGroup: Object, withProperties: ["a", "e", "length", "valueOf", "__proto__", "b"])
    const v203 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v203 = .object(ofGroup: Object, withProperties: ["toString", "d", "__proto__", "b", "e"])
    const v209 = {b:Uint16Array,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
    // v209 = .object(ofGroup: Object, withProperties: ["valueOf", "b", "e", "length", "__proto__", "a"])
    const v210 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
    // v210 = .object(ofGroup: Object, withProperties: ["e", "d", "__proto__", "toString", "b"])
    const v214 = [13.37,13.37,13.37,13.37,13.37];
    // v214 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v216 = [1337];
    // v216 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v217 = [v214,v216,Uint16Array];
    // v217 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v221 = [13.37,13.37];
    // v221 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v223 = [1337,1337,1337,1337];
    // v223 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v224 = "object".constructor;
    // v224 = .function()
    const v228 = [1337];
    // v228 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v230 = [13.37,13.37,13.37,13.37,13.37];
    // v230 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    let v232 = v230;
    const v233 = 1337 == 13.37;
    // v233 = .boolean
    const v235 = Object();
    // v235 = .object()
    const v236 = v223.toString();
    // v236 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
    const v237 = [13.37,v221];
    // v237 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v238 = {d:gc,valueOf:v223};
    // v238 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
    let v239 = 1337;
    let v241 = v224;
    v216.__proto__ = v235;
    const v243 = Symbol.match;
    // v243 = .object(ofGroup: Symbol, withProperties: ["__proto__", "description"])
    Symbol[v243] = v243;
    const v244 = Object();
    // v244 = .object()
    const v248 = new Uint8Array(28499);
    // v248 = .object(ofGroup: Uint8Array, withProperties: ["length", "byteOffset", "buffer", "__proto__", "constructor", "byteLength"], withMethods: ["keys", "findIndex", "filter", "indexOf", "reduceRight", "sort", "map", "some", "subarray", "reduce", "fill", "lastIndexOf", "set", "values", "entries", "reverse", "every", "includes", "join", "slice", "copyWithin", "forEach", "find"])
    const v249 = Object(13.37,1337);
    // v249 = .object()
    const v250 = v235.length;
    // v250 = .unknown
    "iterator".length = Uint16Array;
    const v251 = this && v228;
    // v251 = .boolean
    const v252 = v216.__proto__;
    // v252 = .object()
    "iterator"[4294967297] = v239;
    let v256 = 0;
    const v257 = v256 + 1;
    // v257 = .primitive
    v256 = v257;
    const v258 = [1337];
    // v258 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    let v261 = 0;
    const v263 = [1337,1337];
    // v263 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v264 = v261 + 1;
    // v264 = .primitive
    v261 = v264;
    let v267 = 0;
    v258.length = 6;
    const v269 = v267 + 1;
    // v269 = .primitive
    v267 = v269;
}
const v272 = [1337];
// v272 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
let v273 = v272;
const v274 = v16(v273);
// v274 = .unknown
const v275 = v16(1024,4.0);
// v275 = .unknown
}
%NeverOptimizeFunction(main);
main();
