function main() {
const v4 = [13.37,13.37,13.37];
// v4 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v6 = [1337];
// v6 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v7 = [3156875969,3156875969,1337,DataView];
// v7 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v8 = {constructor:v7,c:v7,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v8 = .object(ofGroup: Object, withProperties: ["a", "c", "constructor", "d", "__proto__", "e"])
const v9 = {e:DataView,constructor:1337,valueOf:1337,d:v7};
// v9 = .object(ofGroup: Object, withProperties: ["valueOf", "e", "d", "constructor", "__proto__"])
let v10 = v6;
const v15 = [13.37,13.37,13.37];
// v15 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v17 = [1337];
// v17 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v18 = [3156875969,3156875969,1337,DataView];
// v18 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v19 = {constructor:v18,c:v18,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v19 = .object(ofGroup: Object, withProperties: ["constructor", "c", "__proto__", "d", "e", "a"])
const v20 = {e:DataView,constructor:1337,valueOf:1337,d:v18};
// v20 = .object(ofGroup: Object, withProperties: ["d", "constructor", "e", "__proto__", "valueOf"])
let v21 = v17;
const v26 = [13.37,13.37];
// v26 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v28 = [1337,1337,1337,1337];
// v28 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v33 = [13.37,13.37,13.37];
// v33 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v35 = [1337];
// v35 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v36 = [3156875969,3156875969,1337,DataView];
// v36 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v37 = {constructor:v36,c:v36,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v37 = .object(ofGroup: Object, withProperties: ["a", "c", "constructor", "e", "__proto__", "d"])
const v38 = {e:DataView,constructor:1337,valueOf:1337,d:v36};
// v38 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "d", "valueOf", "e"])
let v39 = v35;
const v44 = [371375.4036167406,371375.4036167406,371375.4036167406];
// v44 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v46 = [1337];
// v46 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v47 = [3156875969,3156875969,1337,DataView];
// v47 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v48 = {constructor:v47,c:v47,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
// v48 = .object(ofGroup: Object, withProperties: ["a", "c", "constructor", "e", "d", "__proto__"])
const v49 = {e:DataView,constructor:1337,valueOf:1337,d:v47};
// v49 = .object(ofGroup: Object, withProperties: ["d", "constructor", "e", "valueOf", "__proto__"])
let v50 = v46;
const v55 = [13.37,13.37,13.37];
// v55 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v57 = [1337];
// v57 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v58 = [3156875969,3156875969,1337,DataView];
// v58 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v59 = {constructor:v58,c:v58,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v59 = .object(ofGroup: Object, withProperties: ["c", "d", "a", "constructor", "e", "__proto__"])
const v60 = {e:DataView,constructor:1337,valueOf:1337,d:v58};
// v60 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "valueOf", "d", "e"])
const v63 = [13.37,13.37];
// v63 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v65 = [1337,1337,1337,1337];
// v65 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v66 = [13.37,v63];
// v66 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v67 = {c:13.37};
// v67 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
const v68 = {d:gc,valueOf:v65};
// v68 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
let v69 = 1337;
const v70 = v63[1024];
// v70 = .unknown
let v73 = 0;
do {
    const v74 = v70 - 1;
    // v74 = .primitive
    const v75 = v73 + 1;
    // v75 = .primitive
    let v77 = 0;
    v73 = v75;
} while (v73 < 3);
const v82 = [13.37,13.37];
// v82 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v84 = [1337,1337,1337,1337];
// v84 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v85 = "object".constructor;
// v85 = .function()
for (const v86 in "object") {
    const v91 = [13.37,13.37,13.37];
    // v91 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v93 = [1337];
    // v93 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v94 = [3156875969,3156875969,1337,DataView];
    // v94 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v95 = {constructor:v94,c:v94,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v95 = .object(ofGroup: Object, withProperties: ["d", "a", "constructor", "__proto__", "e", "c"])
    const v96 = {e:DataView,constructor:1337,valueOf:1337,d:v94};
    // v96 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "constructor", "d", "e"])
    let v97 = v93;
    const v102 = [13.37,13.37,13.37];
    // v102 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v104 = [1337];
    // v104 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v105 = [3156875969,3156875969,1337,DataView];
    // v105 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v106 = {constructor:v105,c:v105,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v106 = .object(ofGroup: Object, withProperties: ["constructor", "e", "d", "c", "__proto__", "a"])
    const v107 = {e:DataView,constructor:1337,valueOf:1337,d:v105};
    // v107 = .object(ofGroup: Object, withProperties: ["e", "valueOf", "d", "constructor", "__proto__"])
    let v108 = v104;
    const v113 = [13.37,13.37,13.37];
    // v113 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v115 = [1337];
    // v115 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v116 = [3156875969,3156875969,1337,DataView];
    // v116 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v117 = {constructor:v116,c:v116,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v117 = .object(ofGroup: Object, withProperties: ["d", "constructor", "e", "a", "__proto__", "c"])
    const v118 = {e:DataView,constructor:1337,valueOf:1337,d:v116};
    // v118 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "valueOf", "e", "d"])
    let v119 = v115;
    const v124 = [371375.4036167406,371375.4036167406,371375.4036167406];
    // v124 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v126 = [1337];
    // v126 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v127 = [3156875969,3156875969,1337,DataView];
    // v127 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v128 = {constructor:v127,c:v127,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
    // v128 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "a", "c", "d", "e"])
    const v129 = {e:DataView,constructor:1337,valueOf:1337,d:v127};
    // v129 = .object(ofGroup: Object, withProperties: ["valueOf", "constructor", "e", "d", "__proto__"])
    let v130 = v126;
    const v135 = [13.37,13.37,13.37];
    // v135 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v137 = [1337];
    // v137 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v138 = [3156875969,3156875969,1337,DataView];
    // v138 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v139 = {constructor:v138,c:v138,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v139 = .object(ofGroup: Object, withProperties: ["e", "a", "__proto__", "c", "constructor", "d"])
    const v140 = {e:DataView,constructor:1337,valueOf:1337,d:v138};
    // v140 = .object(ofGroup: Object, withProperties: ["d", "valueOf", "e", "__proto__", "constructor"])
    let v141 = v137;
    const v146 = [13.37,13.37,13.37];
    // v146 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v148 = [1337];
    // v148 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v149 = [3156875969,3156875969,1337,DataView];
    // v149 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v150 = {constructor:v149,c:v149,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v150 = .object(ofGroup: Object, withProperties: ["constructor", "d", "c", "__proto__", "e", "a"])
    const v151 = {e:DataView,constructor:1337,valueOf:1337,d:v149};
    // v151 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "d", "valueOf", "e"])
    let v152 = v148;
    const v157 = [13.37,13.37,13.37];
    // v157 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v159 = [1337];
    // v159 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v160 = [3156875969,3156875969,1337,DataView];
    // v160 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v161 = {constructor:v160,c:v160,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v161 = .object(ofGroup: Object, withProperties: ["e", "a", "d", "c", "__proto__", "constructor"])
    const v162 = {e:DataView,constructor:1337,valueOf:1337,d:v160};
    // v162 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "d", "e", "constructor"])
    let v163 = v159;
    const v166 = Object();
    // v166 = .object()
    const v169 = Object(1337,v166,13.37,v151,3156875969);
    // v169 = .object()
    for (let v173 = 0; v173 < 10; v173++) {
        let v175 = 0;
        const v176 = v173 + v150;
        // v176 = .primitive
    }
    const v178 = [13.37,13.37,13.37];
    // v178 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v180 = [1337];
    // v180 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v181 = [3156875969,3156875969,1337,DataView];
    // v181 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v182 = {constructor:v181,c:v166,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v182 = .object(ofGroup: Object, withProperties: ["d", "__proto__", "c", "e", "a", "constructor"])
    const v183 = {e:DataView,constructor:1337,valueOf:1337,d:v181};
    // v183 = .object(ofGroup: Object, withProperties: ["valueOf", "e", "__proto__", "d", "constructor"])
    let v184 = v180;
    const v188 = [13.37,13.37];
    // v188 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    "boolean"[v160] = 1;
    const v190 = [1337,1337,1337,1337];
    // v190 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v191 = [13.37,v188];
    // v191 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v192 = {c:13.37};
    // v192 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v193 = {d:gc,valueOf:v190};
    // v193 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
    let v194 = 1337;
    const v195 = v188[1024];
    // v195 = .unknown
    let v198 = 0;
    for (const v199 in "boolean") {
        let v202 = 0;
        do {
            let v203 = 0;
            try {
                let v206 = 0;
                do {
                    const v208 = v206 + 1;
                    // v208 = .primitive
                    v206 = v208;
                } while (v206 < 7);
                const v209 = v150.__proto__;
                // v209 = .object()
                const v210 = typeof v203;
                // v210 = .string
                const v212 = v210 === "function";
                // v212 = .boolean
                for (let v216 = 0; v216 < 4; v216++) {
                    "function"[v212] = v178;
                }
                const v217 = ["function",v206];
                // v217 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
                v203 = v199;
            } catch(v218) {
                let v219 = v218;
                if (v218) {
                    let v222 = 0;
                    while (v222 < 10) {
                        const v224 = v65[-4070122010];
                        // v224 = .unknown
                        for (let v227 = 0; v227 < 0; v227++) {
                            let v228 = v227;
                        }
                        const v229 = v222 + 1;
                        // v229 = .primitive
                        v222 = v229;
                    }
                    v219 = v219;
                } else {
                    let v230 = v183;
                    let v232 = 0;
                    const v233 = v232 + 1;
                    // v233 = .primitive
                    try {
                        const v234 = "boolean".slice(1337,0);
                        // v234 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
                        v230 = v218;
                    } catch(v235) {
                        const v236 = [v148];
                        // v236 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
                        v230 = v151;
                    }
                    v219 = v230;
                }
                v203 = v203;
            }
            const v237 = v202 + 1;
            // v237 = .primitive
            v202 = v237;
        } while (v202 < 8);
    }
    const v238 = 1337 < 0;
    // v238 = .boolean
    do {
        const v239 = v198 + 1;
        // v239 = .primitive
        v198 = v239;
    } while (v198 < 3);
    const v244 = [13.37,13.37];
    // v244 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v246 = [1337,1337,1337,1337];
    // v246 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v247 = "object".constructor;
    // v247 = .function()
    for (const v248 in "object") {
        const v249 = ~v244;
        // v249 = .boolean
    }
    const v250 = v246 + 1;
    // v250 = .primitive
    const v251 = v246.toString();
    // v251 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
    "object"[1] = 1337;
    const v252 = [13.37,v244];
    // v252 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v253 = {c:13.37};
    // v253 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v254 = {d:gc,valueOf:v246};
    // v254 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
    let v255 = 1337;
    const v257 = Object();
    // v257 = .object()
    v198 = 3;
    const v258 = {__proto__:3,constructor:v198,d:v192,valueOf:v195,length:13.37};
    // v258 = .object(ofGroup: Object, withProperties: ["constructor", "length", "__proto__", "valueOf", "d"])
    const v263 = [13.37,13.37];
    // v263 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v265 = [1337,1337,1337,1337];
    // v265 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v266 = [13.37,v263];
    // v266 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v267 = {c:13.37};
    // v267 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v268 = {d:gc,valueOf:v265};
    // v268 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
    let v269 = 1337;
    const v270 = v263[1024];
    // v270 = .unknown
    let v273 = 0;
    do {
        const v274 = (3)[v20];
        // v274 = .unknown
        v116.__proto__ = v274;
        const v275 = v270 - 1;
        // v275 = .primitive
        const v276 = v273 + 1;
        // v276 = .primitive
        v273 = v276;
    } while (v273 < 3);
    const v281 = [13.37,13.37];
    // v281 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v283 = [1337,1337,1337,1337];
    // v283 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v284 = "object".constructor;
    // v284 = .function()
    for (const v285 in "object") {
        const v286 = ~v281;
        // v286 = .boolean
    }
    const v287 = v283 + 1;
    // v287 = .primitive
    const v288 = v283.toString();
    // v288 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
    "object"[1] = 1337;
    const v289 = [13.37,v281];
    // v289 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    const v290 = v85(v129,1337,v251);
    // v290 = .unknown
    v36[16] = 13.37;
    v246[1] = v113;
    const v291 = {c:13.37};
    // v291 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v292 = {d:gc,valueOf:v283};
    // v292 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
    let v293 = 1337;
    const v295 = Object();
    // v295 = .object()
    v273 = 3;
    const v296 = {__proto__:3,constructor:v273,d:v267,valueOf:v270,length:13.37};
    // v296 = .object(ofGroup: Object, withProperties: ["valueOf", "d", "__proto__", "length", "constructor"])
    v273 = v293;
    const v298 = gc();
    // v298 = .undefined
    v106.valueOf = Object;
    const v299 = Object(3156875969,v269,3156875969,1337);
    // v299 = .object()
    const v300 = v284(v161,v160,v96,v238);
    // v300 = .unknown
    const v301 = ~v82;
    // v301 = .boolean
    const v305 = [1337];
    // v305 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
    let v306 = v305;
    "object"[1] = 1337;
}
const v307 = v84 + 1;
// v307 = .primitive
const v308 = v84.toString();
// v308 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
"object"[1] = 1337;
const v309 = [13.37,v82];
// v309 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v310 = {c:13.37};
// v310 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
const v311 = {d:gc,valueOf:v84};
// v311 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
let v312 = 1337;
const v314 = Object();
// v314 = .object()
v73 = 3;
const v315 = {__proto__:3,constructor:v73,d:v67,valueOf:v70,length:13.37};
// v315 = .object(ofGroup: Object, withProperties: ["length", "constructor", "valueOf", "d", "__proto__"])
const v317 = Object(v55,1337,v309);
// v317 = .object()
const v318 = "object".constructor;
// v318 = .function()
for (const v319 in "object") {
    const v320 = ~v26;
    // v320 = .boolean
}
const v321 = v28 + 1;
// v321 = .primitive
const v322 = v28.toString();
// v322 = .string + .object(ofGroup: String, withProperties: ["constructor", "length", "__proto__"], withMethods: ["includes", "indexOf", "startsWith", "codePointAt", "split", "slice", "concat", "trim", "substring", "charCodeAt", "endsWith", "replace", "padStart", "repeat", "padEnd", "charAt", "lastIndexOf"])
"object"[1] = 1337;
const v323 = [13.37,v26];
// v323 = .object(ofGroup: Array, withProperties: ["__proto__", "length", "constructor"], withMethods: ["slice", "toLocaleString", "join", "sort", "some", "find", "toString", "reduceRight", "pop", "concat", "fill", "unshift", "splice", "reverse", "findIndex", "filter", "copyWithin", "indexOf", "keys", "includes", "entries", "every", "values", "shift", "map", "flatMap", "push", "lastIndexOf", "flat", "reduce", "forEach"])
const v324 = {c:13.37};
// v324 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
const v325 = {d:gc,valueOf:v28};
// v325 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
let v326 = 1337;
const v328 = Object();
// v328 = .object()
v310[4294967297] = v314;
const v329 = {e:13.37};
// v329 = .object(ofGroup: Object, withProperties: ["e", "__proto__"])
const v330 = v37 || v73;
// v330 = .boolean
let v331 = v67;
const v332 = gc();
// v332 = .undefined
}
%NeverOptimizeFunction(main);
main();
