function main() {
const v4 = [13.37];
// v4 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v6 = [1337,1337];
// v6 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v7 = [-3132770439,1337,1337];
// v7 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v8 = {constructor:v6,d:v6,a:v7,toString:1337,c:v4};
// v8 = .object(ofGroup: Object, withProperties: ["toString", "__proto__", "d", "constructor", "a", "c"])
const v9 = {constructor:Map,length:13.37,valueOf:v6,b:1337,a:-3132770439};
// v9 = .object(ofGroup: Object, withProperties: ["length", "b", "constructor", "a", "valueOf", "__proto__"])
let v10 = 1337;
const v15 = [13.37,13.37,13.37,13.37,13.37];
// v15 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v17 = [1337];
// v17 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v18 = [-1151066323,v17,isFinite];
// v18 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v19 = {toString:13.37,c:v17,__proto__:v18,valueOf:"tTpktw/d77",constructor:"tTpktw/d77",length:v17};
// v19 = .object(ofGroup: Object, withProperties: ["c", "constructor", "valueOf", "length", "toString", "__proto__"])
const v20 = {toString:13.37};
// v20 = .object(ofGroup: Object, withProperties: ["toString", "__proto__"])
let v21 = 1337;
const v28 = [1337,13.37,"DwTSpuldnd"];
// v28 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v30 = new Uint8Array(v28);
// v30 = .object(ofGroup: Uint8Array, withProperties: ["byteLength", "__proto__", "constructor", "buffer", "length", "byteOffset"], withMethods: ["indexOf", "every", "some", "includes", "reduce", "sort", "find", "keys", "subarray", "slice", "reduceRight", "fill", "copyWithin", "findIndex", "join", "forEach", "filter", "entries", "map", "set", "lastIndexOf", "values", "reverse"])
const v33 = [13.37,13.37,13.37];
// v33 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v34 = v33[Function];
// v34 = .unknown
const v35 = v30.sort(v34);
// v35 = .undefined
const v37 = [13.37,13.37,13.37,13.37];
// v37 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v39 = [1337,1337,1337];
// v39 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v40 = [986843737];
// v40 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v41 = {constructor:v39,toString:"undefined",valueOf:v37,c:v39,__proto__:1337};
// v41 = .object(ofGroup: Object, withProperties: ["valueOf", "c", "constructor", "toString", "__proto__"])
const v42 = {a:v39,b:v39,__proto__:1337,c:v39,e:v37};
// v42 = .object(ofGroup: Object, withProperties: ["c", "e", "a", "__proto__", "b"])
let v43 = v41;
const v45 = {a:Math};
// v45 = .object(ofGroup: Object, withProperties: ["__proto__", "a"])
const v46 = ~v45;
// v46 = .boolean
let v48 = 0;
let v50 = 0;
const v54 = [13.37,13.37,13.37,13.37];
// v54 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v55 = [v54,-1970853828,DataView];
// v55 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v58 = new Float64Array(8);
// v58 = .object(ofGroup: Float64Array, withProperties: ["constructor", "byteOffset", "__proto__", "byteLength", "buffer", "length"], withMethods: ["entries", "every", "some", "indexOf", "subarray", "lastIndexOf", "findIndex", "keys", "map", "reverse", "reduce", "filter", "sort", "slice", "join", "set", "find", "forEach", "copyWithin", "includes", "reduceRight", "values", "fill"])
const v63 = [13.37,13.37,13.37,13.37];
// v63 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v65 = [1337,1337,1337,1337,1337];
// v65 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v66 = ["UflW1mhflT"];
// v66 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v67 = {length:"UflW1mhflT",a:v65,c:-1663921742,toString:v66,constructor:"UflW1mhflT"};
// v67 = .object(ofGroup: Object, withProperties: ["__proto__", "length", "toString", "a", "c", "constructor"])
const v68 = {length:"UflW1mhflT"};
// v68 = .object(ofGroup: Object, withProperties: ["length", "__proto__"])
let v69 = 13.37;
const v74 = [13.37,13.37,13.37,13.37];
// v74 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v76 = [1337,1337,1337];
// v76 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v77 = [v74,v76,"object"];
// v77 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v78 = {};
// v78 = .object(ofGroup: Object, withProperties: ["__proto__"])
const v79 = {toString:3808353909,d:3808353909,e:3808353909,a:v74};
// v79 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "toString", "d", "a"])
let v80 = v74;
const v85 = [13.37,13.37,13.37];
// v85 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v87 = [1337,1337,1337,1337,1337];
// v87 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v88 = [13.37,-4294967296];
// v88 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v89 = {d:"replace",constructor:13.37,b:13.37,c:"replace",e:-4294967296};
// v89 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "e", "b", "c", "constructor"])
const v90 = {e:-4294967296,constructor:v87,c:v85,valueOf:v87};
// v90 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "c", "e", "valueOf"])
function v91(v92,v93) {
    const v101 = [13.37,13.37,13.37];
    // v101 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v103 = [1337,1337,1337];
    // v103 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v104 = [v101,v101,Infinity,v101];
    // v104 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v105 = {d:1337,e:13.37,__proto__:v104,length:v103};
    // v105 = .object(ofGroup: Object, withProperties: ["d", "length", "e", "__proto__"])
    const v106 = {c:10,constructor:10,valueOf:v101,__proto__:10,toString:"YjXjEe2.bY"};
    // v106 = .object(ofGroup: Object, withProperties: ["constructor", "c", "toString", "__proto__", "valueOf"])
    let v107 = "YjXjEe2.bY";
    const v112 = [13.37,13.37,13.37];
    // v112 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v114 = [];
    // v114 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v115 = {__proto__:"eeeRbEqfAO",constructor:65537,length:v114};
    // v115 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "length"])
    const v116 = {toString:"eeeRbEqfAO",d:13.37,length:v115,__proto__:RegExp,valueOf:65537};
    // v116 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "toString", "length", "valueOf"], withMethods: ["__proto__"])
    let v117 = RegExp;
    const v122 = [-2072135974,-2072135974,-2072135974,-2072135974,-2072135974];
    // v122 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v123 = ["undefined",-807842.3563119042,-807842.3563119042];
    // v123 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v124 = {b:2147483647};
    // v124 = .object(ofGroup: Object, withProperties: ["__proto__", "b"])
    function v125(v126,v127) {
        const v128 = v126 in v125;
        // v128 = .boolean
        const v134 = [926222540,926222540,1337,DataView];
        // v134 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v135 = {constructor:v134,c:v134,e:13.37,d:1337,a:926222540,__proto__:"boolean"};
        // v135 = .object(ofGroup: Object, withProperties: ["a", "constructor", "c", "__proto__", "e", "d"])
        const v136 = {e:DataView,constructor:1337,valueOf:1337,d:v134};
        // v136 = .object(ofGroup: Object, withProperties: ["d", "constructor", "valueOf", "__proto__", "e"])
        for (let v141 = 0; v141 < 10; v141 = v141 + 10) {
        }
        const v143 = [1337];
        // v143 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        let v145 = 0;
        for (const v146 in "boolean") {
            let v149 = 0;
            let v151 = 0;
            const v152 = v151 + 1;
            // v152 = .primitive
            for (let v156 = 0; v156 < 100; v156++) {
            }
            const v159 = [];
            // v159 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
            const v160 = {valueOf:v159,length:13.37,d:127,e:127};
            // v160 = .object(ofGroup: Object, withProperties: ["length", "__proto__", "valueOf", "e", "d"])
            let v161 = v160;
            const v162 = 100 - 1;
            // v162 = .primitive
            const v163 = v161[3];
            // v163 = .unknown
            let v165 = 0;
            for (let v169 = 0; v169 < 0; v169++) {
            }
            try {
            } catch(v170) {
                const v175 = [13.37,13.37,13.37];
                // v175 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v178 = [1337,1337,1337,1337,1337];
                // v178 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v179 = [];
                // v179 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v180 = {__proto__:"eeeRbEqfAO",constructor:65537,length:v179};
                // v180 = .object(ofGroup: Object, withProperties: ["__proto__", "length", "constructor"])
                const v181 = {toString:"eeeRbEqfAO",d:13.37,length:v180,__proto__:RegExp,valueOf:65537};
                // v181 = .object(ofGroup: Object, withProperties: ["valueOf", "d", "length", "toString", "__proto__"], withMethods: ["__proto__"])
                let v182 = RegExp;
                const v187 = [13.37,13.37,13.37,13.37,13.37];
                // v187 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                let v190 = -9007199254740992;
                const v195 = [-1242988596,13.37,13.37,-4294967297];
                // v195 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v197 = [-374203.6377172986,-93687789,v195];
                // v197 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                let v200 = 0;
                while (v200 < 4) {
                    const v201 = v197.push(v190);
                    // v201 = .integer
                    const v202 = v200 + 1;
                    // v202 = .primitive
                    v200 = v202;
                }
                const v203 = [0];
                // v203 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v204 = [v187,v203,Uint8ClampedArray];
                // v204 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v205 = {b:v203,e:Uint8ClampedArray,a:13.37,length:"iterator",valueOf:4294967297};
                // v205 = .object(ofGroup: Object, withProperties: ["length", "e", "a", "__proto__", "b", "valueOf"])
                const v206 = {b:0,e:0,toString:Uint8ClampedArray,d:Uint8ClampedArray};
                // v206 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "e", "toString", "b"])
                let v207 = v187;
                const v212 = [13.37,13.37,13.37,13.37,13.37];
                // v212 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v214 = [1337];
                // v214 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v215 = [v212,v214,Uint16Array];
                // v215 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v219 = Object(13.37,1337);
                // v219 = .object()
                const v220 = {b:v214,e:Uint16Array,a:13.37,length:"iterator",valueOf:4294967297};
                // v220 = .object(ofGroup: Object, withProperties: ["b", "valueOf", "length", "__proto__", "a", "e"])
                const v221 = {b:1337,e:1337,toString:Uint16Array,d:Uint16Array};
                // v221 = .object(ofGroup: Object, withProperties: ["toString", "d", "e", "b", "__proto__"])
                const v223 = [13.37,13.37,13.37,13.37,13.37];
                // v223 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                const v225 = [1337];
                // v225 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                let v226 = v223;
                const v230 = [13.37,13.37];
                // v230 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                for (const v231 in "object") {
                    const v232 = ~v230;
                    // v232 = .boolean
                }
                const v234 = "object".constructor;
                // v234 = .function()
                const v235 = gc + v225;
                // v235 = .primitive
                const v236 = v226 - v234;
                // v236 = .number
                const v238 = [1337];
                // v238 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
                let v239 = v238;
                let v241 = undefined;
                let v243 = 0;
                let v245 = 0;
            }
            const v248 = [13.37];
            // v248 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
            const v252 = v122 & 8;
            // v252 = .integer
            const v253 = v124.__proto__;
            // v253 = .object()
            for (let v254 = 0; v254 < 100; v254++) {
            }
            for (const v255 of "pvU0UUjoya") {
            }
            const v256 = v149 + 1;
            // v256 = .primitive
        }
        const v257 = 926222540 + 1;
        // v257 = .primitive
        for (const v259 in "object") {
        }
        return 0;
    }
    const v261 = [1337];
    // v261 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    let v262 = v261;
    const v263 = [];
    // v263 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v266 = [13.37,13.37];
    // v266 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v267 = [13.37,13.37,-9007199254740992,13.37];
    // v267 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v269 = [1337];
    // v269 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v274 = new Uint16Array(6992);
    // v274 = .object(ofGroup: Uint16Array, withProperties: ["length", "byteLength", "__proto__", "buffer", "constructor", "byteOffset"], withMethods: ["fill", "findIndex", "filter", "entries", "map", "find", "sort", "every", "reduce", "join", "set", "copyWithin", "subarray", "reverse", "some", "indexOf", "includes", "reduceRight", "lastIndexOf", "values", "slice", "keys", "forEach"])
    const v275 = v263.__proto__;
    // v275 = .object()
    v275.__proto__ = v274;
    v267.length = 461300596;
    const v276 = [1071021010,1071021010,1071021010,1071021010];
    // v276 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v278 = [5.0,5.0,5.0];
    // v278 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v279 = [5.0];
    // v279 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v280 = v279.concat(v269,v266,v278,v267,v276);
    // v280 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v281 = v125(v262);
    // v281 = .unknown
    let v293 = 0;
    let v295 = 0;
    const v296 = v295 + 1;
    // v296 = .primitive
    const v361 = Symbol.split;
    // v361 = .object(ofGroup: Symbol, withProperties: ["__proto__", "description"])
    "boolean"[v361] = v85;
    const v363 = !v89;
    // v363 = .boolean
    let v417 = 0;
    const v420 = eval(-3394606452);
    // v420 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["padEnd", "substring", "charAt", "split", "includes", "padStart", "trim", "charCodeAt", "startsWith", "lastIndexOf", "replace", "repeat", "concat", "slice", "indexOf", "endsWith", "codePointAt"])
    const v423 = 4 + 1;
    // v423 = .primitive
    return gc;
}
let v440 = 0;
const v444 = v91();
// v444 = .unknown
let v445 = v90;
const v447 = [1337];
// v447 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
let v448 = v447;
let v450 = undefined;
const v461 = [13.37,13.37,13.37,13.37];
// v461 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v463 = [1337];
// v463 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v464 = [];
// v464 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v465 = {b:-2619420865,constructor:13.37};
// v465 = .object(ofGroup: Object, withProperties: ["b", "constructor", "__proto__"])
const v466 = {d:"isConcatSpreadable"};
// v466 = .object(ofGroup: Object, withProperties: ["__proto__", "d"])
let v467 = -2619420865;
const v472 = [13.37,13.37,13.37,13.37,13.37];
// v472 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v478 = [13.37,13.37,13.37,13.37,13.37];
// v478 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v480 = [1337,1337,1337,1337];
// v480 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v481 = [v478,1337,13.37];
// v481 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v482 = {b:"toStringTag",c:v481};
// v482 = .object(ofGroup: Object, withProperties: ["c", "__proto__", "b"])
const v483 = {valueOf:v480,length:eval};
// v483 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["length"])
let v484 = 1337;
const v489 = [13.37,13.37,13.37];
// v489 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v491 = [1337,1337,1337,1337];
// v491 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v492 = 1337 > eval;
// v492 = .boolean
const v493 = v481[2403828005];
// v493 = .unknown
v483.length = 1337;
const v495 = !v478;
// v495 = .boolean
"toStringTag".c = v483;
const v496 = [Uint8ClampedArray,13.37];
// v496 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v497 = {d:-1024,c:v496,toString:v491,valueOf:v496};
// v497 = .object(ofGroup: Object, withProperties: ["c", "__proto__", "d", "valueOf", "toString"])
const v498 = {c:v497,e:v496,toString:v491};
// v498 = .object(ofGroup: Object, withProperties: ["__proto__", "toString", "c", "e"])
let v499 = Uint8ClampedArray;
let v506 = 0;
const v507 = v506 + 1;
// v507 = .primitive
const v509 = [13.37,13.37];
// v509 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v511 = [1337,1337,1337,1337,1337];
// v511 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v512 = [];
// v512 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v513 = {c:1337,b:-3170815044,d:1337,__proto__:1337};
// v513 = .object(ofGroup: Object, withProperties: ["__proto__", "c", "b", "d"])
const v514 = {e:"__proto__",a:1337,__proto__:eval,constructor:1337,c:v513,b:Math,toString:"__proto__"};
// v514 = .object(ofGroup: Object, withProperties: ["toString", "e", "b", "__proto__", "c", "constructor", "a"], withMethods: ["__proto__"])
let v515 = 13.37;
const v520 = [13.37,13.37,13.37,13.37];
// v520 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v522 = [1337];
// v522 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v523 = [];
// v523 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v524 = {valueOf:v522,__proto__:13.37,a:Number,c:Number,b:Number};
// v524 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["c", "b", "a"])
const v525 = {__proto__:v522,a:v522,constructor:Number,e:13.37,length:"number",b:13.37};
// v525 = .object(ofGroup: Object, withProperties: ["b", "a", "__proto__", "length", "e"], withMethods: ["constructor"])
let v526 = v520;
const v531 = [13.37,13.37];
// v531 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v533 = [1337,1337,1337,1337,1337];
// v533 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v534 = [10,DataView,"symbol"];
// v534 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v535 = {toString:v531,e:"symbol",a:13.37,d:DataView,constructor:v534,valueOf:v531};
// v535 = .object(ofGroup: Object, withProperties: ["d", "__proto__", "a", "constructor", "e", "toString", "valueOf"])
const v536 = {length:v535,a:"symbol"};
// v536 = .object(ofGroup: Object, withProperties: ["__proto__", "a", "length"])
const v540 = [13.37,13.37,13.37,13.37,13.37];
// v540 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v542 = [1337,1337,1337,1337];
// v542 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v543 = [v542];
// v543 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v544 = {constructor:v543,toString:v542,a:v543,c:v543,__proto__:isFinite,length:v543};
// v544 = .object(ofGroup: Object, withProperties: ["a", "constructor", "toString", "__proto__", "length", "c"], withMethods: ["__proto__"])
const v545 = {toString:13.37,length:1337};
// v545 = .object(ofGroup: Object, withProperties: ["__proto__", "toString", "length"])
function v547(v548,v549) {
    const v551 = {__proto__:536870912};
    // v551 = .object(ofGroup: Object, withProperties: ["__proto__"])
    with (v551) {
        let v556 = 0;
        __proto__[0] = v547;
    }
    function v560(v561,v562) {
        for (const v564 in "boolean") {
            for (const v568 in "boolean") {
                let v571 = 0;
                do {
                    const v608 = {__proto__:536870912};
                    // v608 = .object(ofGroup: Object, withProperties: ["__proto__"])
                    const v618 = !1337;
                    // v618 = .boolean
                } while (v571 < 8);
            }
        }
    }
}
const v622 = v547(1024,4.0);
// v622 = .unknown
let v625 = 1903240934;
let v629 = 0;
const v630 = v629 + 1;
// v630 = .primitive
v629 = v630;
const v636 = [1.7976931348623157e+308];
// v636 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v638 = [255,255,255];
// v638 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v639 = {a:255,toString:isFinite,c:v636,__proto__:v638,valueOf:DataView,constructor:"gM8oAednYn"};
// v639 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "a", "valueOf", "c"], withMethods: ["toString"])
const v640 = {toString:v636,valueOf:v639,d:255,constructor:536870912};
// v640 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "valueOf", "toString", "d"])
const v641 = RegExp.apply(v640,RegExp);
// v641 = .unknown
const v642 = "object".split(v641,255);
// v642 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v643 = [13.37,13.37,-4261300175,13.37];
// v643 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v645 = [1337,1337];
// v645 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v646 = ["MAX_VALUE","MAX_VALUE"];
// v646 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v647 = {b:"MAX_VALUE",length:v645,c:v646};
// v647 = .object(ofGroup: Object, withProperties: ["c", "b", "length", "__proto__"])
const v648 = {constructor:v643,c:13.37,d:13.37};
// v648 = .object(ofGroup: Object, withProperties: ["constructor", "d", "__proto__", "c"])
let v649 = v647;
const v651 = [1337,v649,1337,1337];
// v651 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v653 = v651.indexOf(0,v648);
// v653 = .integer
const v655 = {get:eval};
// v655 = .object(ofGroup: Object, withProperties: ["__proto__"], withMethods: ["get"])
const v657 = Object.defineProperty(v482,"e",v655);
// v657 = .undefined
let v660 = 0;
const v661 = v660 + 1;
// v661 = .primitive
v660 = v661;
const v662 = eval("__proto__");
// v662 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["padEnd", "substring", "charAt", "split", "includes", "padStart", "trim", "charCodeAt", "startsWith", "lastIndexOf", "replace", "repeat", "concat", "slice", "indexOf", "endsWith", "codePointAt"])
const v663 = [1337,1337,1337,1337];
// v663 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v664 = [];
// v664 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v665 = {valueOf:v472,a:13.37,toString:"PI",d:v472,b:13.37,e:1000};
// v665 = .object(ofGroup: Object, withProperties: ["d", "e", "valueOf", "b", "toString", "a", "__proto__"])
const v666 = {c:v665,__proto__:parseInt};
// v666 = .object(ofGroup: Object, withProperties: ["c", "__proto__"], withMethods: ["__proto__"])
let v667 = 1337;
const v670 = "symbol".replace("symbol","symbol");
// v670 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["padEnd", "substring", "charAt", "split", "includes", "padStart", "trim", "charCodeAt", "startsWith", "lastIndexOf", "replace", "repeat", "concat", "slice", "indexOf", "endsWith", "codePointAt"])
let v671 = RegExp;
const v673 = new Int16Array(v670);
// v673 = .object(ofGroup: Int16Array, withProperties: ["byteOffset", "buffer", "length", "byteLength", "__proto__", "constructor"], withMethods: ["reverse", "indexOf", "map", "reduceRight", "find", "reduce", "lastIndexOf", "keys", "entries", "values", "copyWithin", "every", "subarray", "fill", "some", "findIndex", "filter", "set", "slice", "join", "forEach", "includes", "sort"])
const v674 = v671.apply(v670,v673);
// v674 = .unknown
let v678 = 10;
const v682 = [13.37,v91];
// v682 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v683 = [13.37,v682];
// v683 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v685 = Function("symbol",v683);
// v685 = .unknown
let v686 = 0;
let v692 = 0;
let v695 = 0;
let v696 = 0;
const v701 = v686 + 1;
// v701 = .primitive
for (let v705 = 0; v705 < 9; v705++) {
    const v707 = Symbol.toStringTag;
    // v707 = .object(ofGroup: Symbol, withProperties: ["__proto__", "description"])
    v85[v707] = v705;
}
const v708 = "object"[-3753695015];
// v708 = .unknown
const v709 = v78 in v43;
// v709 = .boolean
let v712 = 0;
const v713 = v712 + 1;
// v713 = .primitive
v712 = v713;
v88.c = 13.37;
const v714 = new Float64Array(v63);
// v714 = .object(ofGroup: Float64Array, withProperties: ["constructor", "byteOffset", "__proto__", "byteLength", "buffer", "length"], withMethods: ["entries", "every", "some", "indexOf", "subarray", "lastIndexOf", "findIndex", "keys", "map", "reverse", "reduce", "filter", "sort", "slice", "join", "set", "find", "forEach", "copyWithin", "includes", "reduceRight", "values", "fill"])
const v715 = v78[2070038973];
// v715 = .unknown
"object"[-2147483649] = v63;
const v716 = parseInt("object");
// v716 = .integer
const v717 = v58.sort();
// v717 = .undefined
const v718 = Function(v641);
// v718 = .unknown
}
%NeverOptimizeFunction(main);
main();
