function main() {
const v4 = [13.37,13.37,13.37];
// v4 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v6 = [1337];
// v6 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v7 = [3156875969,3156875969,1337,DataView];
// v7 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v8 = {constructor:v7,c:v7,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v8 = .object(ofGroup: Object, withProperties: ["c", "a", "e", "constructor", "__proto__", "d"])
const v9 = {e:DataView,constructor:1337,valueOf:1337,d:v7};
// v9 = .object(ofGroup: Object, withProperties: ["d", "__proto__", "valueOf", "e", "constructor"])
let v10 = v6;
const v15 = [13.37,13.37,13.37];
// v15 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v17 = [1337];
// v17 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v18 = [3156875969,3156875969,1337,DataView];
// v18 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v19 = {constructor:v18,c:v18,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v19 = .object(ofGroup: Object, withProperties: ["a", "__proto__", "d", "c", "e", "constructor"])
const v20 = {e:DataView,constructor:1337,valueOf:1337,d:v18};
// v20 = .object(ofGroup: Object, withProperties: ["e", "valueOf", "d", "__proto__", "constructor"])
let v21 = v17;
const v26 = [13.37,13.37,13.37];
// v26 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v28 = [1337];
// v28 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v29 = [3156875969,3156875969,1337,DataView];
// v29 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v30 = {constructor:v29,c:v29,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v30 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "d", "c", "a", "constructor"])
const v31 = {e:DataView,constructor:1337,valueOf:1337,d:v29};
// v31 = .object(ofGroup: Object, withProperties: ["constructor", "d", "__proto__", "valueOf", "e"])
let v32 = v28;
const v36 = [13.37,13.37];
// v36 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v38 = [1337,1337,1337,1337];
// v38 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v43 = [13.37,13.37,13.37];
// v43 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v45 = [1337];
// v45 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v46 = [3156875969,3156875969,1337,DataView];
// v46 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v47 = {constructor:v46,c:v46,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v47 = .object(ofGroup: Object, withProperties: ["constructor", "d", "c", "e", "a", "__proto__"])
const v48 = {e:DataView,constructor:1337,valueOf:1337,d:v46};
// v48 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "d", "valueOf", "constructor"])
let v49 = v45;
const v54 = [371375.4036167406,371375.4036167406,371375.4036167406];
// v54 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v56 = [1337];
// v56 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v57 = [3156875969,3156875969,1337,DataView];
// v57 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v58 = {constructor:v57,c:v57,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
// v58 = .object(ofGroup: Object, withProperties: ["a", "e", "d", "__proto__", "constructor", "c"])
const v59 = {c:DataView,constructor:1337,valueOf:1337,d:v57};
// v59 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "d", "c", "constructor"])
let v60 = v56;
const v65 = [13.37,13.37,13.37];
// v65 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v67 = [1337];
// v67 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v68 = [3156875969,3156875969,1337,DataView];
// v68 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v69 = {constructor:v68,c:v68,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
// v69 = .object(ofGroup: Object, withProperties: ["e", "d", "c", "constructor", "a", "__proto__"])
const v70 = {e:DataView,constructor:1337,valueOf:1337,d:v68};
// v70 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "constructor", "e", "d"])
const v73 = [13.37,13.37];
// v73 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v75 = [1337,1337,1337,1337];
// v75 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v76 = [13.37,v73];
// v76 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v77 = {c:13.37};
// v77 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
const v78 = {d:gc,valueOf:v75};
// v78 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
let v79 = 1337;
const v80 = v73[1024];
// v80 = .unknown
let v83 = 0;
do {
    const v84 = v80 - 1;
    // v84 = .primitive
    const v85 = v83 + 1;
    // v85 = .primitive
    let v87 = 0;
    v83 = v85;
} while (v83 < 3);
const v92 = [13.37,13.37];
// v92 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v94 = [1337,1337,1337,1337];
// v94 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
const v95 = "object".constructor;
// v95 = .function()
for (const v96 in "object") {
    const v101 = [13.37,13.37,13.37];
    // v101 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v103 = [1337];
    // v103 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v104 = [3156875969,3156875969,1337,DataView];
    // v104 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v105 = {constructor:v104,c:v104,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v105 = .object(ofGroup: Object, withProperties: ["constructor", "c", "a", "__proto__", "e", "d"])
    const v106 = {e:DataView,constructor:1337,valueOf:1337,d:v104};
    // v106 = .object(ofGroup: Object, withProperties: ["constructor", "valueOf", "d", "__proto__", "e"])
    const v111 = [371375.4036167406,371375.4036167406,371375.4036167406];
    // v111 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v113 = [1337];
    // v113 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v114 = [3156875969,3156875969,1337,DataView];
    // v114 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v115 = {constructor:v114,c:v114,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
    // v115 = .object(ofGroup: Object, withProperties: ["constructor", "e", "d", "__proto__", "c", "a"])
    const v116 = {e:DataView,constructor:1337,valueOf:1337,d:v114};
    // v116 = .object(ofGroup: Object, withProperties: ["d", "constructor", "e", "valueOf", "__proto__"])
    let v117 = v113;
    const v122 = [13.37,13.37,13.37];
    // v122 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v124 = [1337];
    // v124 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v125 = [3156875969,3156875969,1337,DataView];
    // v125 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v126 = {constructor:v125,c:v125,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v126 = .object(ofGroup: Object, withProperties: ["__proto__", "a", "c", "constructor", "d", "e"])
    const v127 = {e:DataView,constructor:1337,valueOf:1337,d:v125};
    // v127 = .object(ofGroup: Object, withProperties: ["d", "e", "valueOf", "constructor", "__proto__"])
    let v128 = v124;
    const v131 = [13.37,13.37];
    // v131 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v133 = [1337,1337,1337,1337];
    // v133 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v134 = [13.37,v131];
    // v134 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v135 = {c:13.37};
    // v135 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
    const v136 = {d:gc,valueOf:v133};
    // v136 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
    let v137 = 1337;
    const v138 = v131[1024];
    // v138 = .unknown
    let v141 = 0;
    do {
        const v142 = v138 - 1;
        // v142 = .primitive
        const v143 = v141 + 1;
        // v143 = .primitive
        v141 = v143;
    } while (v141 < 3);
    const v148 = [13.37,13.37];
    // v148 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v150 = [1337,1337,1337,1337];
    // v150 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v151 = "object".constructor;
    // v151 = .function()
    for (const v152 in "object") {
        const v153 = ~v148;
        // v153 = .boolean
        const v158 = [13.37,13.37,13.37];
        // v158 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v160 = [1337];
        // v160 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v161 = [3156875969,3156875969,1337,DataView];
        // v161 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v162 = {constructor:v161,c:v161,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
        // v162 = .object(ofGroup: Object, withProperties: ["a", "d", "__proto__", "constructor", "e", "c"])
        const v163 = {e:DataView,constructor:1337,valueOf:1337,d:v161};
        // v163 = .object(ofGroup: Object, withProperties: ["e", "constructor", "valueOf", "d", "__proto__"])
        let v164 = v160;
        const v169 = [13.37,13.37,13.37];
        // v169 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v171 = [1337];
        // v171 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v172 = [3156875969,3156875969,1337,DataView];
        // v172 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v173 = {constructor:v172,c:v172,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
        // v173 = .object(ofGroup: Object, withProperties: ["e", "constructor", "a", "d", "c", "__proto__"])
        const v174 = {e:DataView,constructor:1337,valueOf:1337,d:v172};
        // v174 = .object(ofGroup: Object, withProperties: ["e", "valueOf", "constructor", "__proto__", "d"])
        let v175 = v171;
        const v178 = [13.37,13.37];
        // v178 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v180 = [1337,1337,1337,1337];
        // v180 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v181 = [13.37,v178];
        // v181 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v182 = {c:"boolean"};
        // v182 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
        const v183 = {d:gc,valueOf:v180};
        // v183 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
        let v184 = 1337;
        const v185 = v178[1024];
        // v185 = .unknown
        let v188 = 0;
        do {
            const v189 = v185 - 1;
            // v189 = .primitive
            const v190 = v188 + 1;
            // v190 = .primitive
            v188 = v190;
        } while (v188 < -4294967295);
        const v195 = [13.37,13.37];
        // v195 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v197 = [1337,1337,1337,1337];
        // v197 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v198 = "object".constructor;
        // v198 = .function()
        for (const v199 in 0) {
            const v200 = ~v195;
            // v200 = .boolean
        }
        const v201 = v197 + 1;
        // v201 = .primitive
        const v202 = v197.toString();
        // v202 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["padEnd", "substring", "charAt", "split", "includes", "padStart", "trim", "charCodeAt", "startsWith", "lastIndexOf", "replace", "repeat", "concat", "slice", "indexOf", "endsWith", "codePointAt"])
        "object"[1] = 1337;
        const v203 = [v125,v195];
        // v203 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
        const v204 = {c:13.37};
        // v204 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
        const v205 = {d:gc,valueOf:v197};
        // v205 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
        let v206 = 1337;
        const v208 = Object();
        // v208 = .object()
        v188 = -4294967295;
        const v209 = {__proto__:-4294967295,constructor:v188,d:"boolean",valueOf:v185,length:13.37};
        // v209 = .object(ofGroup: Object, withProperties: ["d", "length", "__proto__", "constructor", "valueOf"])
    }
    const v211 = v150 + 1;
    // v211 = .primitive
    const v212 = v150.toString();
    // v212 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["padEnd", "substring", "charAt", "split", "includes", "padStart", "trim", "charCodeAt", "startsWith", "lastIndexOf", "replace", "repeat", "concat", "slice", "indexOf", "endsWith", "codePointAt"])
    "object"[1] = 1337;
    const v213 = [13.37,v148];
    // v213 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v214 = {c:13.37};
    // v214 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v215 = {d:gc,valueOf:v150};
    // v215 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"], withMethods: ["d"])
    let v217 = 1337;
    const v219 = Object();
    // v219 = .object()
    v141 = 3;
    const v220 = {__proto__:3,constructor:v141,d:v135,valueOf:v138,length:13.37};
    // v220 = .object(ofGroup: Object, withProperties: ["d", "valueOf", "constructor", "length", "__proto__"])
    let v222 = v103;
    const v227 = [13.37,13.37,13.37];
    // v227 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v229 = [1337];
    // v229 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v230 = [3156875969,3156875969,1337,DataView];
    // v230 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v231 = {constructor:v230,c:v230,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v231 = .object(ofGroup: Object, withProperties: ["constructor", "c", "e", "__proto__", "d", "a"])
    const v232 = {e:DataView,constructor:1337,valueOf:1337,d:v230};
    // v232 = .object(ofGroup: Object, withProperties: ["d", "e", "constructor", "__proto__", "valueOf"])
    let v233 = v229;
    const v238 = [13.37,13.37,13.37];
    // v238 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v240 = [1337];
    // v240 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v241 = [3156875969,3156875969,1337,DataView];
    // v241 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v242 = {constructor:v241,c:v241,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v242 = .object(ofGroup: Object, withProperties: ["a", "e", "__proto__", "d", "c", "constructor"])
    const v243 = {e:DataView,constructor:1337,valueOf:1337,d:v241};
    // v243 = .object(ofGroup: Object, withProperties: ["__proto__", "e", "constructor", "d", "valueOf"])
    let v244 = v240;
    const v249 = [371375.4036167406,371375.4036167406,371375.4036167406];
    // v249 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v251 = [1337];
    // v251 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v252 = [3156875969,3156875969,1337,DataView];
    // v252 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v253 = {constructor:v252,c:v252,e:371375.4036167406,d:1337,a:3156875969,__proto__:"boolean"};
    // v253 = .object(ofGroup: Object, withProperties: ["c", "a", "e", "constructor", "__proto__", "d"])
    const v254 = {e:DataView,constructor:1337,valueOf:1337,d:v252};
    // v254 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "constructor", "valueOf", "d"])
    let v255 = v251;
    const v276 = [3156875969,3156875969,1337,DataView];
    // v276 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v277 = {e:DataView,constructor:1337,valueOf:1337,d:v276};
    // v277 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "d", "constructor", "valueOf"])
    let v284 = 0;
    const v285 = v284 + 1;
    // v285 = .primitive
    v284 = v285;
    v277.constructor = 13.37;
    let v295 = 0;
    const v296 = Object.prototype;
    // v296 = .object()
    const v297 = v295 + 1;
    // v297 = .primitive
    v295 = v297;
    const v298 = [13.37,13.37,13.37];
    // v298 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v301 = [1337];
    // v301 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    for (let v305 = 0; v305 < 0; v305++) {
    }
    const v307 = v298.toLocaleString();
    // v307 = .string + .object(ofGroup: String, withProperties: ["length", "constructor", "__proto__"], withMethods: ["padEnd", "substring", "charAt", "split", "includes", "padStart", "trim", "charCodeAt", "startsWith", "lastIndexOf", "replace", "repeat", "concat", "slice", "indexOf", "endsWith", "codePointAt"])
    v92.length = 2;
    const v309 = [1337];
    // v309 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v310 = [3156875969,3156875969,1337,DataView];
    // v310 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v311 = {constructor:v310,c:v310,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v311 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "c", "e", "d", "a"])
    const v312 = {e:DataView,constructor:1337,valueOf:1337,d:v310};
    // v312 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "d", "e", "valueOf"])
    let v313 = v309;
    const v318 = [13.37,13.37,13.37];
    // v318 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v320 = [1337];
    // v320 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v321 = [3156875969,3156875969,1337,DataView];
    // v321 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v322 = {constructor:v321,c:v321,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v322 = .object(ofGroup: Object, withProperties: ["a", "__proto__", "e", "constructor", "d", "c"])
    const v323 = {e:DataView,constructor:1337,valueOf:1337,d:v321};
    // v323 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__", "d", "e", "constructor"])
    let v324 = v320;
    const v329 = [13.37,v70,13.37];
    // v329 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v331 = [1337];
    // v331 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v332 = [3156875969,3156875969,1337,DataView];
    // v332 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v333 = {constructor:v332,c:v332,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v333 = .object(ofGroup: Object, withProperties: ["a", "__proto__", "d", "e", "constructor", "c"])
    const v334 = {e:DataView,constructor:1337,valueOf:1337,d:v332};
    // v334 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "constructor", "e", "valueOf"])
    let v335 = v331;
    const v338 = Object();
    // v338 = .object()
    const v341 = Object(1337,v338,13.37,v323,3156875969);
    // v341 = .object()
    for (let v345 = 0; v345 < 10; v345++) {
        const v346 = v345 + v322;
        // v346 = .primitive
    }
    const v348 = [1337];
    // v348 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    let v349 = v348;
    const v351 = [13.37,13.37,13.37];
    // v351 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v353 = [1337];
    // v353 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    let v354 = v353;
    v354[0] = v353;
    const v357 = [13.37,13.37,13.37];
    // v357 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v359 = [1337];
    // v359 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v360 = [3156875969,3156875969,1337,DataView];
    // v360 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v361 = {constructor:v360,c:v338,e:13.37,d:1337,a:3156875969,__proto__:"boolean"};
    // v361 = .object(ofGroup: Object, withProperties: ["a", "__proto__", "e", "constructor", "d", "c"])
    const v362 = {e:DataView,constructor:1337,valueOf:1337,d:v360};
    // v362 = .object(ofGroup: Object, withProperties: ["valueOf", "e", "constructor", "__proto__", "d"])
    let v363 = v359;
    const v367 = [13.37,13.37];
    // v367 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    "boolean"[v332] = 1;
    const v369 = [1337,1337,1337,1337];
    // v369 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v370 = [13.37,v367];
    // v370 = .object(ofGroup: Array, withProperties: ["length", "__proto__", "constructor"], withMethods: ["copyWithin", "reduceRight", "concat", "every", "some", "toString", "filter", "toLocaleString", "slice", "map", "join", "values", "sort", "indexOf", "keys", "splice", "fill", "includes", "pop", "reduce", "lastIndexOf", "find", "flatMap", "findIndex", "unshift", "flat", "reverse", "shift", "entries", "forEach", "push"])
    const v371 = {c:13.37};
    // v371 = .object(ofGroup: Object, withProperties: ["c", "__proto__"])
    const v372 = {d:gc,valueOf:v369};
    // v372 = .object(ofGroup: Object, withProperties: ["valueOf", "__proto__"], withMethods: ["d"])
    let v373 = 1337;
    const v374 = v367[1024];
    // v374 = .unknown
    let v377 = 0;
    for (const v378 in "boolean") {
        let v381 = 0;
        do {
            try {
                let v384 = 0;
                const v385 = v384 + 1;
                // v385 = .primitive
                v384 = v385;
                for (let v390 = 0; v390 < 4; v390++) {
                }
            } catch(v391) {
                if (v391) {
                    let v394 = 0;
                    for (let v398 = 0; v398 < 0; v398++) {
                    }
                } else {
                    try {
                    } catch(v399) {
                    }
                }
            }
            const v400 = v381 + 1;
            // v400 = .primitive
            v381 = v400;
        } while (v381 < 8);
    }
    const v401 = v377 + 1;
    // v401 = .primitive
    v377 = v401;
    let v415 = 0;
    const v416 = v415 + 1;
    // v416 = .primitive
    v415 = v416;
}
}
%NeverOptimizeFunction(main);
main();
