function main() {
const v4 = [13.37,13.37,13.37,13.37];
// v4 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v6 = [1337,1337,1337];
// v6 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v7 = ["ZXLxh4*16R",Infinity];
// v7 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v8 = {c:"ZXLxh4*16R",e:1337};
// v8 = .object(ofGroup: Object, withProperties: ["e", "__proto__", "c"])
const v9 = {};
// v9 = .object(ofGroup: Object, withProperties: ["__proto__"])
let v10 = v6;
const v15 = [13.37,13.37,13.37,13.37,13.37];
// v15 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v17 = [1337,1337,1337];
// v17 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v18 = [v17,v15,4294967297,v15];
// v18 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v19 = {e:13.37,length:13.37,valueOf:13.37,constructor:v18,c:Float64Array,__proto__:13.37};
// v19 = .object(ofGroup: Object, withProperties: ["__proto__", "constructor", "valueOf", "e", "c", "length"])
const v20 = {b:v19,valueOf:13.37,length:1337};
// v20 = .object(ofGroup: Object, withProperties: ["length", "valueOf", "__proto__", "b"])
let v21 = 13.37;
const v26 = [13.37,13.37,13.37,13.37,13.37];
// v26 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v28 = [1337,1337,1337];
// v28 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v29 = [13.37,"toPrimitive",3981912834];
// v29 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v30 = {toString:3981912834,valueOf:Int8Array};
// v30 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf", "toString"])
const v31 = {valueOf:v28};
// v31 = .object(ofGroup: Object, withProperties: ["__proto__", "valueOf"])
let v32 = 1337;
const v37 = [13.37,13.37,13.37];
// v37 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v39 = [1337,1337,1337,1337];
// v39 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v40 = [9007199254740992,Int32Array,Int32Array];
// v40 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v41 = {constructor:Int32Array,d:v40,valueOf:v37,e:v39,__proto__:v37,toString:v40,b:"function"};
// v41 = .object(ofGroup: Object, withProperties: ["constructor", "b", "toString", "valueOf", "d", "__proto__", "e"])
const v42 = {e:v41,b:Int32Array,constructor:"function",valueOf:9007199254740992,toString:v40};
// v42 = .object(ofGroup: Object, withProperties: ["b", "toString", "e", "constructor", "valueOf", "__proto__"])
let v43 = 9007199254740992;
const v48 = [13.37,13.37,13.37,13.37];
// v48 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v50 = [1337];
// v50 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v51 = [13.37,1337,Uint32Array];
// v51 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v52 = {__proto__:-1635377947};
// v52 = .object(ofGroup: Object, withProperties: ["__proto__"])
const v53 = {toString:v48,b:13.37};
// v53 = .object(ofGroup: Object, withProperties: ["__proto__", "toString", "b"])
let v54 = v51;
const v59 = [13.37,13.37,13.37];
// v59 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v61 = [4096,4096,4096];
// v61 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v62 = [4096,"e"];
// v62 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v63 = {a:13.37,d:v59,c:4096,b:2,length:v59};
// v63 = .object(ofGroup: Object, withProperties: ["length", "__proto__", "d", "a", "b", "c"])
const v64 = {constructor:4096,d:13.37,c:v61,toString:v59};
// v64 = .object(ofGroup: Object, withProperties: ["constructor", "c", "d", "__proto__", "toString"])
let v65 = v61;
const v69 = [13.37,13.37,13.37,13.37,13.37];
// v69 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v71 = [1337,1337,1337,1337,1337];
// v71 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v72 = [v71,v69,v69,13.37];
// v72 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v73 = {__proto__:v72,c:v72};
// v73 = .object(ofGroup: Object, withProperties: ["__proto__", "c"])
const v74 = {e:"yjSMDGTCed",c:v73,valueOf:eval,b:1337};
// v74 = .object(ofGroup: Object, withProperties: ["c", "e", "b", "__proto__"], withMethods: ["valueOf"])
const v77 = [13.37,13.37,13.37];
// v77 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
function v78(v79,v80) {
    const v83 = Object.freeze(arguments);
    // v83 = .undefined
    return Object;
}
const v84 = ["undefined",v77];
// v84 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v86 = [1337];
// v86 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
let v87 = v86;
const v88 = v78(...v84,...v87);
// v88 = .unknown
let v89 = "yjSMDGTCed";
let v94 = 0;
const v95 = v94 + 1;
// v95 = .primitive
const v97 = [13.37,13.37];
// v97 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v99 = [4096,4096,4096,4096,4096];
// v99 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v100 = {c:4096,b:13.37,d:4096,c:4096};
// v100 = .object(ofGroup: Object, withProperties: ["__proto__", "d", "c", "b"])
const v101 = {e:"__proto__",a:4096,__proto__:"__proto__",constructor:4096,c:v100,b:Math,toString:"__proto__"};
// v101 = .object(ofGroup: Object, withProperties: ["constructor", "toString", "a", "__proto__", "b", "c", "e"])
let v102 = 13.37;
const v106 = [13.37,13.37,13.37,13.37];
// v106 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v108 = [1337];
// v108 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v109 = [];
// v109 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v112 = new Int16Array(16);
// v112 = .object(ofGroup: Int16Array, withProperties: ["__proto__", "buffer", "length", "byteLength", "byteOffset", "constructor"], withMethods: ["keys", "reduce", "indexOf", "map", "set", "join", "slice", "reduceRight", "lastIndexOf", "entries", "values", "reverse", "sort", "find", "findIndex", "forEach", "every", "some", "copyWithin", "fill", "includes", "subarray", "filter"])
const v115 = new Int8Array(v112);
// v115 = .object(ofGroup: Int8Array, withProperties: ["byteOffset", "constructor", "buffer", "byteLength", "__proto__", "length"], withMethods: ["values", "copyWithin", "fill", "join", "keys", "sort", "entries", "forEach", "subarray", "some", "map", "reduceRight", "reduce", "lastIndexOf", "filter", "findIndex", "reverse", "every", "set", "includes", "find", "slice", "indexOf"])
const v116 = {valueOf:v108,__proto__:13.37,a:Uint8Array,c:Uint8Array,b:Uint8Array};
// v116 = .object(ofGroup: Object, withProperties: ["c", "valueOf", "a", "__proto__", "b"])
const v117 = {__proto__:v108,a:v108,constructor:Uint8Array,e:13.37,length:"number",b:13.37};
// v117 = .object(ofGroup: Object, withProperties: ["e", "length", "a", "b", "__proto__", "constructor"])
let v118 = v106;
const v123 = [810791.8581587574,810791.8581587574];
// v123 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v125 = [1337,1337,1337,1337,1337];
// v125 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v126 = [10,DataView,"symbol"];
// v126 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v127 = {toString:v123,e:"symbol",a:810791.8581587574,d:DataView,constructor:v126,valueOf:v123};
// v127 = .object(ofGroup: Object, withProperties: ["toString", "constructor", "d", "valueOf", "e", "a", "__proto__"])
const v128 = {length:v127,a:"symbol"};
// v128 = .object(ofGroup: Object, withProperties: ["__proto__", "a", "length"])
let v129 = 10;
const v134 = [13.37,13.37,13.37,13.37,13.37];
// v134 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v136 = 1337 & v48;
// v136 = .integer
const v137 = [1337,1337,1337,1337];
// v137 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v138 = [v137];
// v138 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v139 = {constructor:v138,toString:v137,a:v138,c:v138,__proto__:isFinite,length:v138};
// v139 = .object(ofGroup: Object, withProperties: ["c", "constructor", "length", "__proto__", "toString", "a"], withMethods: ["__proto__"])
const v140 = {toString:13.37,length:1337};
// v140 = .object(ofGroup: Object, withProperties: ["length", "__proto__", "toString"])
let v141 = -4261300175;
function v143(v144,v145) {
    const v147 = {__proto__:536870912};
    // v147 = .object(ofGroup: Object, withProperties: ["__proto__"])
    with (v147) {
        __proto__[0] = v143;
    }
    for (const v167 in v109) {
        const v168 = 13.37 || v167;
        // v168 = .boolean
    }
    const v169 = v145 | v144;
    // v169 = .integer
    let v171 = 255;
    let v175 = 0;
    const v179 = v175 | v171;
    // v179 = .integer
}
const v205 = v143(1024,4.0);
// v205 = .unknown
const v209 = [13.37,13.37,9007199254740992,13.37,13.37];
// v209 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
let v210 = v209;
const v213 = new Float32Array(v210);
// v213 = .object(ofGroup: Float32Array, withProperties: ["byteOffset", "byteLength", "constructor", "buffer", "length", "__proto__"], withMethods: ["filter", "every", "fill", "copyWithin", "slice", "includes", "entries", "reduceRight", "indexOf", "sort", "map", "lastIndexOf", "find", "values", "reverse", "reduce", "findIndex", "join", "keys", "some", "set", "subarray", "forEach"])
v213.constructor = Int16Array;
const v216 = v213.slice(-9007199254740993,1337);
// v216 = .object(ofGroup: Float32Array, withProperties: ["__proto__", "byteOffset", "byteLength", "buffer", "length", "constructor"], withMethods: ["every", "subarray", "join", "lastIndexOf", "findIndex", "reverse", "map", "entries", "find", "keys", "set", "indexOf", "reduce", "some", "includes", "copyWithin", "sort", "slice", "forEach", "reduceRight", "values", "filter", "fill"])
let v218 = 1903240934;
const v220 = new Int8Array(v137);
// v220 = .object(ofGroup: Int8Array, withProperties: ["byteOffset", "constructor", "buffer", "byteLength", "__proto__", "length"], withMethods: ["values", "copyWithin", "fill", "join", "keys", "sort", "entries", "forEach", "subarray", "some", "map", "reduceRight", "reduce", "lastIndexOf", "filter", "findIndex", "reverse", "every", "set", "includes", "find", "slice", "indexOf"])
const v226 = [1.7976931348623157e+308];
// v226 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v228 = [255,255,255];
// v228 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v229 = {a:255,toString:isFinite,c:v226,__proto__:v228,valueOf:"object",constructor:"gM8oAednYn"};
// v229 = .object(ofGroup: Object, withProperties: ["constructor", "__proto__", "a", "c", "valueOf"], withMethods: ["toString"])
for (let v234 = 0; v234 < 100; v234++) {
    const v235 = isFinite();
    // v235 = .boolean
}
let v237 = 0;
const v240 = [1337];
// v240 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v244 = [v240,3609309068,13.37];
// v244 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v246 = [1337];
// v246 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
const v247 = {a:3609309068,c:"6UX*hLOH3D"};
// v247 = .object(ofGroup: Object, withProperties: ["a", "c", "__proto__"])
const v248 = {e:1337,__proto__:v244,constructor:1337,a:v246,c:"6UX*hLOH3D",valueOf:v247};
// v248 = .object(ofGroup: Object, withProperties: ["constructor", "e", "c", "__proto__", "a", "valueOf"])
const v249 = v248[-2147483647];
// v249 = .unknown
const v251 = new Float64Array(v248);
// v251 = .object(ofGroup: Float64Array, withProperties: ["byteOffset", "length", "buffer", "byteLength", "constructor", "__proto__"], withMethods: ["lastIndexOf", "forEach", "find", "indexOf", "copyWithin", "filter", "every", "some", "reduceRight", "join", "values", "reduce", "includes", "reverse", "entries", "slice", "map", "sort", "set", "keys", "subarray", "findIndex", "fill"])
const v252 = v251.sort(v249);
// v252 = .undefined
const v255 = [13.37];
// v255 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
function v256(v257,v258,v259,v260) {
    'use strict'
    const v262 = {};
    // v262 = .object(ofGroup: Object, withProperties: ["__proto__"])
    const v267 = [2153514987,13.37,13.37,13.37,v255];
    // v267 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
    v72[2] = -3170815044;
    const v270 = {length:13.37,b:"NEGATIVE_INFINITY",valueOf:v267,__proto__:v260};
    // v270 = .object(ofGroup: Object, withProperties: ["length", "b", "__proto__", "valueOf"])
    const v271 = {a:1337,toString:v262,constructor:"NEGATIVE_INFINITY",valueOf:v270,b:13.37,c:JSON,e:JSON};
    // v271 = .object(ofGroup: Object, withProperties: ["a", "constructor", "valueOf", "e", "__proto__", "c", "toString", "b"])
    const v273 = JSON.stringify(v271,Reflect,"byteOffset");
    // v273 = .string + .object(ofGroup: String, withProperties: ["length", "__proto__", "constructor"], withMethods: ["trim", "endsWith", "split", "charAt", "padStart", "codePointAt", "substring", "charCodeAt", "replace", "lastIndexOf", "includes", "repeat", "indexOf", "slice", "startsWith", "concat", "padEnd"])
    return v73;
}
const v274 = v256(v237,3,8,v255);
// v274 = .unknown
const v275 = {toString:v226,valueOf:v229,d:255,constructor:536870912};
// v275 = .object(ofGroup: Object, withProperties: ["toString", "valueOf", "constructor", "__proto__", "d"])
const v276 = RegExp.apply(v275,RegExp);
// v276 = .unknown
const v277 = "object".split(v276,255);
// v277 = .object(ofGroup: Array, withProperties: ["constructor", "__proto__", "length"], withMethods: ["pop", "flatMap", "push", "values", "toLocaleString", "indexOf", "copyWithin", "lastIndexOf", "find", "unshift", "keys", "toString", "findIndex", "some", "reduceRight", "reduce", "entries", "splice", "shift", "slice", "concat", "fill", "sort", "includes", "forEach", "filter", "every", "join", "flat", "reverse", "map"])
v61.toString = v256;
const v278 = {constructor:v89,e:v17,valueOf:1.7976931348623157e+308,...v117,...v10,...v54,...v249};
// v278 = .object(ofGroup: Object, withProperties: ["e", "length", "a", "valueOf", "__proto__", "b", "constructor"], withMethods: ["reverse", "map", "keys", "join", "slice", "find", "indexOf", "push", "includes", "lastIndexOf", "toString", "reduceRight", "some", "every", "sort", "copyWithin", "flatMap", "toLocaleString", "shift", "values", "splice", "concat", "unshift", "filter", "forEach", "flat", "fill", "reduce", "entries", "pop", "findIndex"])
v43 = 4294967297;
const v279 = v143(536870912);
// v279 = .unknown
}
%NeverOptimizeFunction(main);
main();
